import snapshot from './site-config.json';
import {defaultLogo,defaultModelLighting,type EnvironmentMap,type LogoSettings,type ModelLighting} from './logo-settings';
export type Work={id:string;title:string;category:string;year:string;role:string;description:string;poster:string;video:string;visible:boolean};
export type Track={id:string;title:string;artist:string;album:string;playlist:string;url:string;cover:string;filename?:string;playlists?:string[]};
export type TeamMember={id:string;name:string;role:string;instagram:string;photo:string;works:string[];visible:boolean};
export type Config={mainLogo:LogoSettings;showTeam:boolean;teamHeadline:string;teamMembers:TeamMember[];musicPlaylists:string[];hdriEnvironments:EnvironmentMap[];aboutLighting:ModelLighting;aboutHeadline:string;aboutMediaType:string;aboutImage:string;aboutModel:string;modelReturnToCenter:boolean;modelReturnBounce:number;modelScale:number;modelAutoRotate:boolean;modelDrag:boolean;modelReact:boolean;modelZoom:boolean;modelSpeed:number;modelSensitivity:number;modelAnimate:boolean;modelAnimation:string;modelExposure:number;modelRotateX:number;modelRotateY:number;modelRotateZ:number;modelOffsetX:number;modelOffsetY:number;backgroundType:string;backgroundImage:string;backgroundVideo:string;backgroundOpacity:number;backgroundDim:number;pattern:string;patternSize:number;patternColor:string;patternOpacity:number;navOpacity:number;name:string;eyebrow:string;headline:string;subtitle:string;about:string;email:string;instagram:string;heroPoster:string;heroVideo:string;logo:string;theme:string;accent:string;font:string;fontSize:number;spacing:number;radius:number;blur:number;glass:number;motion:number;depth:number;columns:number;autoplay:boolean;showAbout:boolean;showMusic:boolean;musicAutoplay:boolean;musicRandomStart:boolean;volume:number;works:Work[];tracks:Track[]};
const original:Config={mainLogo:defaultLogo,showTeam:true,teamHeadline:'People behind\nthe image.',teamMembers:[],musicPlaylists:[],hdriEnvironments:[],aboutLighting:{...defaultModelLighting},aboutHeadline:'Less noise.\nMore feeling.',aboutMediaType:'image',aboutImage:'',aboutModel:'',modelReturnToCenter:true,modelReturnBounce:.55,modelScale:1,modelAutoRotate:true,modelDrag:true,modelReact:true,modelZoom:true,modelSpeed:20,modelSensitivity:18,modelAnimate:true,modelAnimation:'auto',modelExposure:1,modelRotateX:0,modelRotateY:0,modelRotateZ:0,modelOffsetX:0,modelOffsetY:0,backgroundType:'none',backgroundImage:'',backgroundVideo:'',backgroundOpacity:100,backgroundDim:20,pattern:'none',patternSize:32,patternColor:'#888888',patternOpacity:12,navOpacity:46,name:'ICONIC',eyebrow:'INDEPENDENT FILM DIRECTOR',headline:'A different\npoint of view.',subtitle:'Film. Direction. Moving images.',about:'장면의 분위기부터 마지막 컷의 리듬까지. 패션, 공연, 브랜드의 순간을 촬영하고 편집합니다.',email:'',instagram:'',heroPoster:'/editorial.jpg',heroVideo:'',logo:'',theme:'light',accent:'#536bf2',font:'Arial, Helvetica, sans-serif',fontSize:16,spacing:80,radius:22,blur:24,glass:70,motion:1,depth:12,columns:2,autoplay:true,showAbout:true,showMusic:true,musicAutoplay:false,musicRandomStart:false,volume:60,works:[{id:'1',title:'Between the frames',category:'Fashion film',year:'2026',role:'Direction / Cinematography / Edit',description:'공간과 움직임, 그리고 그 사이의 순간. 작품 파일을 업로드해 나만의 필름으로 교체하세요.',poster:'/editorial.jpg',video:'/sample.mp4',visible:true},{id:'2',title:'Selected moments',category:'Brand film',year:'2026',role:'Direction / Edit',description:'새로운 시선으로 기록한 장면들. 현재 재생되는 영상은 기능 확인용 샘플입니다.',poster:'/editorial.jpg',video:'/sample.mp4',visible:true}],tracks:[]};

export function normalizeConfig(value:unknown={}){
 const stored=value as Partial<Config>&{mainLogo?:Partial<LogoSettings>};
 const aboutLighting=stored.aboutLighting?{...defaultModelLighting,...stored.aboutLighting}:{...defaultModelLighting,exposure:stored.modelExposure??defaultModelLighting.exposure};
 const storedLogo:Partial<LogoSettings>=stored.mainLogo||{};
 const logoLighting=storedLogo.modelLighting?{...defaultModelLighting,...storedLogo.modelLighting}:{...defaultModelLighting,exposure:storedLogo.modelExposure??defaultModelLighting.exposure};
 return {...original,...stored,aboutLighting,hdriEnvironments:stored.hdriEnvironments||[],teamMembers:Array.isArray(stored.teamMembers)?stored.teamMembers:[],mainLogo:{...defaultLogo,...storedLogo,modelLighting:logoLighting}} as Config;
}
export const initial:Config=normalizeConfig(snapshot);
