import snapshot from './site-config.json';
import {defaultLogo,defaultModelLighting,type EnvironmentMap,type LogoSettings,type ModelLighting} from './logo-settings';
export type Work={id:string;title:string;category:string;year:string;role:string;description:string;poster:string;video:string;visible:boolean};
export type Track={id:string;title:string;artist:string;album:string;playlist:string;url:string;cover:string;filename?:string;playlists?:string[]};
export type TeamMember={id:string;name:string;role:string;bio:string;instagram:string;photo:string;works:string[];visible:boolean;photoRadius:number;photoSize:number;portfolioSlug:string;portfolioTitle:string;portfolioIntro:string;portfolioLayout:'grid'|'slider';portfolioColumns:number;portfolioGap:number;portfolioRadius:number};
export type Config={mainLogo:LogoSettings;navWorkLabel:string;navAboutLabel:string;navTeamLabel:string;navContactLabel:string;heroCaption:string;heroButtonLabel:string;workKicker:string;workAside:string;aboutKicker:string;aboutDisciplines:string;teamKicker:string;footerAdminLabel:string;heroOffsetY:number;logoOffsetY:number;workOffsetX:number;workOffsetY:number;aboutOffsetX:number;aboutOffsetY:number;teamOffsetX:number;teamOffsetY:number;teamHeadlineX:number;teamHeadlineY:number;teamHeadlineSize:number;teamHeadlineWidth:number;teamMediaSize:number;teamMediaRadius:number;teamRowGap:number;showTeam:boolean;teamHeadline:string;teamMembers:TeamMember[];musicPlaylists:string[];hdriEnvironments:EnvironmentMap[];aboutLighting:ModelLighting;aboutHeadline:string;aboutMediaType:string;aboutImage:string;aboutModel:string;modelReturnToCenter:boolean;modelReturnBounce:number;modelScale:number;modelAutoRotate:boolean;modelDrag:boolean;modelReact:boolean;modelZoom:boolean;modelSpeed:number;modelSensitivity:number;modelAnimate:boolean;modelAnimation:string;modelExposure:number;modelRotateX:number;modelRotateY:number;modelRotateZ:number;modelOffsetX:number;modelOffsetY:number;backgroundType:string;backgroundImage:string;backgroundVideo:string;backgroundOpacity:number;backgroundDim:number;pattern:string;patternSize:number;patternColor:string;patternOpacity:number;navOpacity:number;name:string;eyebrow:string;headline:string;subtitle:string;about:string;email:string;instagram:string;heroPoster:string;heroVideo:string;logo:string;theme:string;accent:string;font:string;fontSize:number;spacing:number;radius:number;blur:number;glass:number;motion:number;depth:number;columns:number;autoplay:boolean;showAbout:boolean;showMusic:boolean;musicAutoplay:boolean;musicRandomStart:boolean;volume:number;works:Work[];tracks:Track[]};
const original:Config={mainLogo:defaultLogo,navWorkLabel:'Work',navAboutLabel:'About',navTeamLabel:'Team',navContactLabel:'Contact',heroCaption:'ICONIC / DIRECTOR’S CUT',heroButtonLabel:'Watch film',workKicker:'01 / SELECTED WORK',workAside:'A collection of perspectives.\n2025 — 2026',aboutKicker:'02 / BEHIND THE LENS',aboutDisciplines:'Direction\nCinematography\nEditing',teamKicker:'03 / PEOPLE',footerAdminLabel:'admin',heroOffsetY:0,logoOffsetY:0,workOffsetX:0,workOffsetY:0,aboutOffsetX:0,aboutOffsetY:0,teamOffsetX:0,teamOffsetY:0,teamHeadlineX:0,teamHeadlineY:0,teamHeadlineSize:92,teamHeadlineWidth:72,teamMediaSize:250,teamMediaRadius:22,teamRowGap:72,showTeam:true,teamHeadline:'People behind\nthe image.',teamMembers:[],musicPlaylists:[],hdriEnvironments:[],aboutLighting:{...defaultModelLighting},aboutHeadline:'Less noise.\nMore feeling.',aboutMediaType:'image',aboutImage:'',aboutModel:'',modelReturnToCenter:true,modelReturnBounce:.55,modelScale:1,modelAutoRotate:true,modelDrag:true,modelReact:true,modelZoom:true,modelSpeed:20,modelSensitivity:18,modelAnimate:true,modelAnimation:'auto',modelExposure:1,modelRotateX:0,modelRotateY:0,modelRotateZ:0,modelOffsetX:0,modelOffsetY:0,backgroundType:'none',backgroundImage:'',backgroundVideo:'',backgroundOpacity:100,backgroundDim:20,pattern:'none',patternSize:32,patternColor:'#888888',patternOpacity:12,navOpacity:46,name:'ICONIC',eyebrow:'INDEPENDENT FILM DIRECTOR',headline:'A different\npoint of view.',subtitle:'Film. Direction. Moving images.',about:'장면의 분위기부터 마지막 컷의 리듬까지. 패션, 공연, 브랜드의 순간을 촬영하고 편집합니다.',email:'',instagram:'',heroPoster:'/editorial.jpg',heroVideo:'',logo:'',theme:'light',accent:'#536bf2',font:'Arial, Helvetica, sans-serif',fontSize:16,spacing:80,radius:22,blur:24,glass:70,motion:1,depth:12,columns:2,autoplay:true,showAbout:true,showMusic:true,musicAutoplay:false,musicRandomStart:false,volume:60,works:[{id:'1',title:'Between the frames',category:'Fashion film',year:'2026',role:'Direction / Cinematography / Edit',description:'공간과 움직임, 그리고 그 사이의 순간. 작품 파일을 업로드해 나만의 필름으로 교체하세요.',poster:'/editorial.jpg',video:'/sample.mp4',visible:true},{id:'2',title:'Selected moments',category:'Brand film',year:'2026',role:'Direction / Edit',description:'새로운 시선으로 기록한 장면들. 현재 재생되는 영상은 기능 확인용 샘플입니다.',poster:'/editorial.jpg',video:'/sample.mp4',visible:true}],tracks:[]};

export function normalizeConfig(value:unknown={}){
 const stored=value as Partial<Config>&{mainLogo?:Partial<LogoSettings>};
 const aboutLighting=stored.aboutLighting?{...defaultModelLighting,...stored.aboutLighting}:{...defaultModelLighting,exposure:stored.modelExposure??defaultModelLighting.exposure};
 const storedLogo:Partial<LogoSettings>=stored.mainLogo||{};
 const logoLighting=storedLogo.modelLighting?{...defaultModelLighting,...storedLogo.modelLighting}:{...defaultModelLighting,exposure:storedLogo.modelExposure??defaultModelLighting.exposure};
 const teamMembers=Array.isArray(stored.teamMembers)?stored.teamMembers.map((member,index)=>{
  const name=typeof member?.name==='string'?member.name:'';
  const fallbackSlug=(name||('member-'+(index+1))).toLowerCase().trim().replace(/[^a-z0-9가-힣]+/g,'-').replace(/^-+|-+$/g,'')||('member-'+(index+1));
  return {...member,
    bio:typeof member?.bio==='string'?member.bio:'',
    photoRadius:Number.isFinite(member?.photoRadius)?member.photoRadius:(stored.teamMediaRadius??original.teamMediaRadius),
    photoSize:Number.isFinite(member?.photoSize)?member.photoSize:(stored.teamMediaSize??original.teamMediaSize),
    works:Array.isArray(member?.works)?member.works:[],
    portfolioSlug:typeof member?.portfolioSlug==='string'&&member.portfolioSlug.trim()?member.portfolioSlug:fallbackSlug,
    portfolioTitle:typeof member?.portfolioTitle==='string'&&member.portfolioTitle.trim()?member.portfolioTitle:'Selected works',
    portfolioIntro:typeof member?.portfolioIntro==='string'?member.portfolioIntro:'',
    portfolioLayout:member?.portfolioLayout==='slider'?'slider':'grid',
    portfolioColumns:Number.isFinite(member?.portfolioColumns)?Math.min(4,Math.max(1,member.portfolioColumns)):3,
    portfolioGap:Number.isFinite(member?.portfolioGap)?Math.min(48,Math.max(4,member.portfolioGap)):14,
    portfolioRadius:Number.isFinite(member?.portfolioRadius)?Math.min(48,Math.max(0,member.portfolioRadius)):18
  };
}):[];
 return {...original,...stored,aboutLighting,hdriEnvironments:stored.hdriEnvironments||[],teamMembers,mainLogo:{...defaultLogo,...storedLogo,modelLighting:logoLighting}} as Config;
}
export const initial:Config=normalizeConfig(snapshot);
