'use client';
import {useState,type Dispatch,type SetStateAction} from 'react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Config} from './defaults';
import {defaultLogo,type LogoSettings} from './logo-settings';
import MainLogo from './main-logo';
import ModelLightingEditor from './model-lighting-editor';
import {uploadFile} from './media-upload';
export default function LogoEditor({draft,setDraft,busy,setBusy,notify}:{draft:Config;setDraft:Dispatch<SetStateAction<Config>>;busy:boolean;setBusy:(v:boolean)=>void;notify:(v:string)=>void}){
 const l={...defaultLogo,...draft.mainLogo};const [animations,setAnimations]=useState<string[]>([]),[reset,setReset]=useState(0);
 const set=(key:keyof LogoSettings,value:unknown)=>setDraft(d=>({...d,mainLogo:{...defaultLogo,...d.mainLogo,[key]:value}}));
 const range=(key:keyof LogoSettings,label:string,min:number,max:number,step=1)=><label className="field">{label}<span className="val">{String(l[key])}</span><Slider aria-label={label} value={[Number(l[key])]} min={min} max={max} step={step} onValueChange={v=>set(key,v[0])}/></label>;
 const toggle=(key:keyof LogoSettings,label:string)=><label className="toggle">{label}<Switch checked={Boolean(l[key])} onCheckedChange={v=>set(key,v)}/></label>;
 const choice=(key:keyof LogoSettings,label:string,options:[string,string][])=><label className="field">{label}<Select value={String(l[key])} onValueChange={v=>set(key,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select></label>;
 async function upload(file:File|undefined,type:'image'|'3d'){if(!file)return;setBusy(true);if(type==='3d')notify('3D 파일을 준비하고 중앙에 맞추는 중입니다…');try{const url=await uploadFile(file);setDraft(d=>({...d,mainLogo:{...defaultLogo,...d.mainLogo,type,[type==='image'?'image':'model']:url,...(type==='3d'?{offsetX:0,offsetY:0,size:1,rotate:0,width:95,modelRotateX:0,modelRotateY:0,modelRotateZ:0}:{})}}));setAnimations([]);notify('메인 로고를 업로드했습니다. 미리보기 후 저장 & 적용을 눌러 주세요.')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 return <div className="logo-editor"><section className="editor-card logo-live-preview"><div className="logo-preview-heading"><h3>메인 로고 미리보기</h3><button className="secondary-button" onClick={()=>setReset(v=>v+1)}>위치 / 재생 초기화</button></div><MainLogo key={reset} config={draft} onAnimations={setAnimations}/></section><div className="editor-grid"><section className="editor-card"><h3>로고 파일 & 크기</h3>{choice('type','메인 로고 종류',[['text','사이트 이름 텍스트'],['image','JPG / PNG 이미지'],['3d','3D 모델']])}<label className="field file-upload">메인 이미지 로고 업로드<input type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>upload(e.target.files?.[0],'image')}/>{l.image&&<><span className="uploaded-file">이미지 등록됨</span><button className="file-clear" onClick={()=>set('image','')}>이미지 제거</button></>}</label><label className="field file-upload">3D 로고 파일 하나 업로드<input type="file" accept=".glb,.gltf,.fbx,.obj,.stl,.ply,.zip" disabled={busy} onChange={e=>upload(e.target.files?.[0],'3d')}/>{l.model&&<><span className="uploaded-file">3D 등록됨</span><button className="file-clear" onClick={()=>set('model','')}>3D 제거</button></>}</label><p>JPG·PNG / GLB·glTF·FBX·OBJ·STL·PLY·ZIP을 지원합니다. 파일당 최대 100MB. 외부 텍스처가 있으면 모델과 관련 파일을 ZIP 하나로 올려 주세요. 단독 OBJ·STL·PLY는 기본 재질로 표시됩니다.</p>{range('height','데스크톱 영역 높이 (px)',120,640)}{range('mobileHeight','모바일 영역 높이 (px)',80,400)}{range('width','로고 너비 (%)',15,150)}{range('size','로고 확대 배율',.3,2,.05)}{choice('fit','이미지 맞춤',[['contain','전체 표시'],['cover','영역 채우기']])}{range('opacity','로고 불투명도',10,100)}{toggle('invert','색 반전')}{toggle('grayscale','흑백')}{choice('blend','배경과 혼합',[['normal','일반'],['difference','반전 혼합'],['screen','스크린'],['multiply','곱하기']])}</section>
 <section className="editor-card"><h3>무한 가로 흐름</h3>{toggle('marquee','로고를 복제해 무한으로 흘리기')}{choice('direction','흐름 방향',[['left','왼쪽으로'],['right','오른쪽으로']])}{range('speed','이동 속도 (px/초)',0,250)}{range('copies','최소 복제 수 (한 묶음)',1,l.type==='3d'?4:16)}{range('gap','복제 사이 공백 (px)',0,400)}{toggle('pauseOnHover','마우스를 올리면 흐름 일시정지')}{toggle('drag','마우스 / 터치 드래그 허용')}<p>무한 흐름은 화면을 채운 두 묶음을 이어 반복합니다. 작은 로고는 빈 구간이 생기지 않도록 자동으로 추가 복제합니다. 드래그하면 흐름을 직접 밀 수 있습니다. 3D는 한 묶음에 최대 4개까지 복제합니다.</p><h3 className="logo-section-heading">마우스 반응</h3>{toggle('pointer','마우스 위치에 따라 기울기')}{range('tilt','기울기 강도 (°)',0,25)}{range('smoothing','반응의 부드러움 (ms)',20,400,10)}{range('hoverScale','호버 시 확대 배율',1,1.2,.01)}{toggle('returnToCenter','놓으면 원위치로 탄력 있게 복귀')}{range('returnBounce','복귀 탄력',0,1,.05)}{range('rotate','기본 회전 (°)',-180,180)}{range('offsetX','가로 위치 (px)',-200,200)}{range('offsetY','세로 위치 (px)',-100,100)}</section>
 <section className="editor-card"><h3>애니메이션 & 빛</h3>{choice('effect','로고 애니메이션',[['none','없음'],['float','천천히 떠오르기'],['pulse','부드러운 숨쉬기'],['sway','좌우 흔들림'],['rotate','회전'],['flip','3D 뒤집기'],['wave','물결 이동']])}{range('duration','한 주기 시간 (초)',1,20,.5)}{range('amount','움직임 크기',0,40)}{range('glow','글로우 크기 (px)',0,40)}<label className="field">글로우 색상<input type="color" value={l.glowColor} onChange={e=>set('glowColor',e.target.value)}/></label>{range('shadow','그림자 크기',0,50)}<p>가로 흐름, 마우스 반응과 애니메이션을 함께 적용할 수 있습니다. 위의 미리보기를 드래그해 바로 확인하세요.</p></section>
 <section className="editor-card"><h3>3D 로고 디테일</h3><button className="secondary-button logo-center-button" onClick={()=>{setDraft(d=>({...d,mainLogo:{...defaultLogo,...d.mainLogo,offsetX:0,offsetY:0,size:1,rotate:0,width:95}}));setReset(v=>v+1)}}>자동 중앙 맞춤</button>{toggle('modelAutoRotate','3D 자동회전')}{range('modelSpeed','3D 회전 속도 (°/초)',-90,90)}{toggle('modelZoom','3D 휠 / 핀치 확대')}{toggle('modelAnimate','3D 내장 애니메이션 재생')}{choice('modelAnimation','내장 애니메이션',[...new Set(['auto',l.modelAnimation,...animations])].map(v=>[v,v==='auto'?'자동 선택':v]))}{range('modelRotateX','3D X축 기본 회전',-180,180)}{range('modelRotateY','3D Y축 기본 회전',-180,180)}{range('modelRotateZ','3D Z축 기본 회전',-180,180)}<p>3D 단일 로고는 드래그로 회전·이동하고, 놓으면 잡기 전 각도와 원위치로 복귀합니다. 무한 흐름에서는 드래그로 가로 흐름을 이동합니다.</p></section><ModelLightingEditor title="Main Logo" value={l.modelLighting} onChange={value=>set('modelLighting',value)} environments={draft.hdriEnvironments} onEnvironmentsChange={value=>setDraft(d=>({...d,hdriEnvironments:value}))} busy={busy} setBusy={setBusy} notify={notify}/><ModelLightingEditor title="About 3D Model" value={draft.aboutLighting} onChange={value=>setDraft(d=>({...d,aboutLighting:value}))} environments={draft.hdriEnvironments} onEnvironmentsChange={value=>setDraft(d=>({...d,hdriEnvironments:value}))} busy={busy} setBusy={setBusy} notify={notify}/></div></div>
}
