'use client';
import {useEffect,useMemo,useRef,type CSSProperties} from 'react';
import {Config} from './defaults';
import {defaultLogo,wrapLogoOffset} from './logo-settings';
import ModelScene from './model-scene';
import useCompactLayout from './use-compact-layout';
import {springStep} from './spring';
export default function MainLogo({config:c,onAnimations}:{config:Config;onAnimations?:(a:string[])=>void}){
 const compact=useCompactLayout();
 const l=useMemo(()=>({...defaultLogo,...c.mainLogo}),[c.mainLogo]);const root=useRef<HTMLDivElement>(null),track=useRef<HTMLDivElement>(null),group=useRef<HTMLDivElement>(null),pose=useRef<HTMLDivElement>(null);
 const state=useRef({offset:0,distance:0,hover:false,visible:true,drag:false,pointerId:-1,px:0,py:0,rx:0,ry:0,x:0,y:0,velocity:0,lastX:0,lastY:0,lastTime:0,actualX:0,actualY:0,actualRX:0,actualRY:0,scale:1,vx:0,vy:0,vrx:0,vry:0,returning:false});
 useEffect(()=>{const node=root.current,g=group.current;if(!node||!g)return;const resize=new ResizeObserver(entries=>{for(const e of entries){if(e.target===node)node.style.setProperty('--logo-tile-width',`${Math.max(80,e.contentRect.width*Math.max(l.type==='3d'&&l.marquee?25:15,l.width)/100)}px`);if(e.target===g){state.current.distance=e.borderBoxSize?.[0]?.inlineSize||g.offsetWidth;state.current.offset=wrapLogoOffset(state.current.offset,state.current.distance)}}});resize.observe(node);resize.observe(g);const io=new IntersectionObserver(es=>{state.current.visible=es[0]?.isIntersecting??true});io.observe(node);return()=>{resize.disconnect();io.disconnect()}},[l.width,l.copies,l.marquee,l.type]);
 useEffect(()=>{const s=state.current;s.x=s.y=s.rx=s.ry=s.actualX=s.actualY=s.actualRX=s.actualRY=s.velocity=0;s.scale=1;s.vx=s.vy=s.vrx=s.vry=0;s.returning=false;s.offset=wrapLogoOffset(s.offset,s.distance)},[l.type,l.image,l.model,l.marquee]);
 useEffect(()=>{let id=0,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const tick=(now:number)=>{const dt=Math.min(40,now-(last||now-16));last=now;const s=state.current;if(s.visible&&!document.hidden){const moving=c.motion>0&&!reduced.matches;if(l.marquee){if(moving&&!s.drag&&!(s.hover&&l.pauseOnHover))s.offset+=(l.direction==='left'?-1:1)*l.speed*dt/1000;if(!s.drag&&Math.abs(s.velocity)>.02){s.offset+=s.velocity*dt/16;s.velocity*=Math.exp(-dt/180)}s.offset=wrapLogoOffset(s.offset,s.distance);if(track.current)track.current.style.transform=`translate3d(${s.offset}px,0,0)`}else if(track.current)track.current.style.transform='none';const k=1-Math.exp(-dt/Math.max(20,l.smoothing));if(s.returning&&moving){for(const[a,b,v]of[['actualX','x','vx'],['actualY','y','vy'],['actualRX','rx','vrx'],['actualRY','ry','vry']] as const){const axis={value:s[a],velocity:s[v]};s[a]=springStep(axis,s[b],dt,l.returnBounce);s[v]=axis.velocity}if(Math.abs(s.actualX-s.x)+Math.abs(s.actualY-s.y)+Math.abs(s.actualRX-s.rx)+Math.abs(s.actualRY-s.ry)<.001&&Math.abs(s.vx)+Math.abs(s.vy)+Math.abs(s.vrx)+Math.abs(s.vry)<.01)s.returning=false}else{s.actualX+=(s.x-s.actualX)*k;s.actualY+=(s.y-s.actualY)*k;s.actualRX+=(s.rx-s.actualRX)*k;s.actualRY+=(s.ry-s.actualRY)*k}s.scale+=((s.hover&&moving?l.hoverScale:1)-s.scale)*k;if(pose.current)pose.current.style.transform=`translate3d(${s.actualX+l.offsetX}px,${s.actualY+l.offsetY}px,0) rotateX(${moving?s.actualRX:0}deg) rotateY(${moving?s.actualRY:0}deg) rotateZ(${l.rotate}deg) scale(${compact&&l.type==='3d'?1:l.size*s.scale})`}id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[l,c.motion,compact]);
 const react=(e:React.PointerEvent<HTMLDivElement>)=>{const s=state.current;if(s.drag){if(e.pointerId!==s.pointerId)return;const dx=e.clientX-s.lastX,dy=e.clientY-s.lastY,dt=Math.max(8,e.timeStamp-s.lastTime);if(l.marquee){s.offset+=dx;s.velocity=dx*16/dt}else{s.x=Math.max(-180,Math.min(180,s.x+dx));s.y=Math.max(-80,Math.min(80,s.y+dy))}s.lastX=e.clientX;s.lastY=e.clientY;s.lastTime=e.timeStamp;return}if(s.returning||!l.pointer||c.motion===0||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();s.rx=-((e.clientY-r.top)/r.height-.5)*l.tilt*2;s.ry=((e.clientX-r.left)/r.width-.5)*l.tilt*2};
 const release=(id:number)=>{const s=state.current;if(s.pointerId!==id)return;s.drag=false;s.pointerId=-1;const node=root.current;if(node?.hasPointerCapture(id))node.releasePointerCapture(id);if(l.returnToCenter){if(!l.marquee)s.x=s.y=0;s.rx=s.ry=0;s.returning=true}if(node)node.dataset.dragging='false'};
 const end=(e:React.PointerEvent<HTMLDivElement>)=>release(e.pointerId);
 useEffect(()=>{const up=(e:PointerEvent)=>release(e.pointerId);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',up,true);return()=>{window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',up,true)}},[l.returnToCenter,l.marquee]);
 const copies=l.marquee?Math.max(Math.ceil(100/Math.max(l.type==='3d'?25:15,l.width)),Math.min(l.type==='3d'?4:16,l.copies)):1;
 const modelConfig:Config={...c,aboutModel:l.model,aboutLighting:l.modelLighting,modelScale:compact&&l.type==='3d'?Math.max(.05,l.size):1,modelReturnToCenter:l.returnToCenter,modelReturnBounce:l.returnBounce,modelDrag:l.drag&&!l.marquee,modelReact:false,modelZoom:l.modelZoom,modelAutoRotate:l.modelAutoRotate,modelSpeed:l.modelSpeed,modelAnimate:l.modelAnimate,modelAnimation:l.modelAnimation,modelExposure:l.modelLighting.exposure,modelRotateX:l.modelRotateX,modelRotateY:l.modelRotateY,modelRotateZ:l.modelRotateZ,modelOffsetX:0,modelOffsetY:0};
 const item=(i:number,duplicate=false)=><div className="logo-tile" key={i} aria-hidden="true"><div className={'logo-effect effect-'+l.effect}>{l.type==='image'&&l.image?<img src={l.image} alt="" draggable={false} style={{objectFit:l.fit}}/>:l.type==='3d'&&l.model?<ModelScene config={modelConfig} outerScale={compact?1:l.size*Math.max(1,l.hoverScale)} onAnimations={i===0&&!duplicate?onAnimations:undefined}/>:<span className="logo-word">{c.name}</span>}</div></div>;
 const style={'--logo-height':l.height+'px','--logo-mobile-height':l.mobileHeight+'px','--logo-gap':l.gap+'px','--logo-duration':l.duration+'s','--logo-amount':l.amount+'px','--logo-angle':Math.min(30,l.amount)+'deg','--logo-pulse-scale':1+l.amount/400,opacity:l.opacity/100,mixBlendMode:l.blend,filter:`invert(${l.invert?1:0}) grayscale(${l.grayscale?1:0}) drop-shadow(0 0 ${l.glow}px ${l.glow?l.glowColor:'transparent'}) drop-shadow(0 ${l.shadow/4}px ${l.shadow}px ${l.shadow?'#0005':'transparent'})`} as CSSProperties;
 return <div ref={root} data-logo-type={l.type} data-logo-marquee={l.marquee?'true':'false'} className={'main-logo '+(l.marquee?'is-marquee ':'')+(l.drag?'is-draggable ':'')+(c.motion===0?'motion-off':'')} style={style} tabIndex={l.drag?0:undefined} role="group" aria-label={`${c.name} 메인 로고${l.drag?' · 드래그 또는 좌우 방향키로 이동':''}`} onPointerEnter={()=>state.current.hover=true} onPointerLeave={()=>{state.current.hover=false;if(l.returnToCenter&&!state.current.drag){state.current.rx=state.current.ry=0;state.current.returning=true}}} onPointerMove={react} onPointerDown={e=>{if(!l.drag||!e.isPrimary||(e.pointerType==='mouse'&&e.button!==0)||(e.target instanceof Element&&e.target.closest('button')))return;const s=state.current;if(s.drag)return;s.pointerId=e.pointerId;s.drag=true;s.returning=false;s.vx=s.vy=s.vrx=s.vry=0;s.velocity=0;s.lastX=e.clientX;s.lastY=e.clientY;s.lastTime=e.timeStamp;if(l.type!=='3d'||l.marquee)e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.dataset.dragging='true'}} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onKeyDown={e=>{if(e.target!==e.currentTarget||!l.drag||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const delta=e.key==='ArrowLeft'?-60:60;if(l.marquee)state.current.offset+=delta;else state.current.x=Math.max(-180,Math.min(180,state.current.x+delta))}}>
 <h1 className="logo-accessible">{c.name}</h1><div ref={pose} className="logo-pose"><div ref={track} className="logo-track"><div ref={group} className="logo-group">{Array.from({length:copies},(_,i)=>item(i))}</div>{l.marquee&&<div className="logo-group" aria-hidden="true">{Array.from({length:copies},(_,i)=>item(i,true))}</div>}</div></div></div>
}
