'use client';
import {useState,useRef,useEffect,useMemo,Dispatch,SetStateAction,CSSProperties} from 'react';
import {DndContext,DragOverlay,closestCenter,MouseSensor,TouchSensor,KeyboardSensor,useSensor,useSensors,DragEndEvent} from '@dnd-kit/core';
import {SortableContext,useSortable,verticalListSortingStrategy,sortableKeyboardCoordinates,arrayMove} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import {GripVertical,Upload,Plus,Trash2,Search,Music2,Film,X,FolderPlus,Check,ChevronUp,ChevronDown} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Pagination,PaginationContent,PaginationItem,PaginationLink} from '@/components/ui/pagination';
import {Config,Track,Work} from './defaults';
import {uploadFile,videoPoster} from './media-upload';
export const playlistsOf=(t:Track)=>t.playlists?.length?t.playlists:t.playlist?[t.playlist]:[];
const membership=(t:Track,names:string[])=>({...t,playlists:[...new Set(names)],playlist:names[0]||''});
type Props={kind:'tracks'|'works'|'focusItems';draft:Config;setDraft:Dispatch<SetStateAction<Config>>;busy:boolean;setBusy:(v:boolean)=>void;notify:(v:string)=>void};
type Media=Track|Work;
function SortRow({item,index,selected,onSelect,active,onEdit,disabled}:{item:Media;index:number;selected:boolean;onSelect:()=>void;active:boolean;onEdit:()=>void;disabled:boolean}){const {setNodeRef,attributes,listeners,transform,transition,isDragging}=useSortable({id:item.id,disabled});const isTrack='artist' in item;return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,opacity:isDragging ? 0.25 : 1}} className={'media-row '+(active?'focused ':'')+(selected?'is-selected':'')}><button className="drag-handle" aria-label={`${item.title} 순서 변경: 잡고 드래그하거나 스페이스 키 사용`} {...attributes} {...listeners}><GripVertical size={20}/></button><Checkbox checked={selected} onCheckedChange={onSelect} aria-label={`${item.title} 선택`}/><button className="row-open" onClick={onEdit}><span className="media-index">{String(index+1).padStart(2,'0')}</span>{isTrack?(item.cover?<img loading="lazy" src={item.cover} alt=""/>:<Music2 size={20}/>):<img loading="lazy" src={item.poster} alt=""/>}<span><strong>{item.title||'Untitled'}</strong><small>{isTrack?`${item.artist||'아티스트 미지정'} · ${playlistsOf(item).join(', ')||'플레이리스트 없음'}`:`${item.category} · ${item.year}`}</small></span></button></div>}
export default function MediaLibrary({kind,draft,setDraft,busy,setBusy,notify}:Props){
 const isMusic=kind==='tracks',isFocus=kind==='focusItems',items=draft[kind] as Media[];const [query,setQuery]=useState(''),[group,setGroup]=useState('All'),[page,setPage]=useState(1),[editing,setEditing]=useState<string|null>(items[0]?.id||null),[selected,setSelected]=useState<Set<string>>(new Set()),[active,setActive]=useState<string|null>(null),[playlistName,setPlaylistName]=useState(''),[bulkArtist,setBulkArtist]=useState(''),[bulkAlbum,setBulkAlbum]=useState(''),[bulkGroup,setBulkGroup]=useState(''),[uploadState,setUploadState]=useState<{done:number;total:number;percent:number;filename:string}|null>(null),[failed,setFailed]=useState<{file:File;error:string}[]>([]);
 const input=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null),working=useRef(false);useEffect(()=>()=>controller.current?.abort(),[]);
 const sensors=useSensors(useSensor(MouseSensor,{activationConstraint:{distance:5}}),useSensor(TouchSensor,{activationConstraint:{delay:200,tolerance:7}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 const names=useMemo(()=>isMusic?[...new Set([...(draft.musicPlaylists||[]),...draft.tracks.flatMap(playlistsOf)])]:[...new Set((items as Work[]).map(w=>w.category))],[draft.musicPlaylists,draft.tracks,items,isMusic]);
 const filtered=items.filter(x=>(group==='All'||(isMusic?playlistsOf(x as Track).includes(group):(x as Work).category===group))&&`${x.title} ${'artist' in x?x.artist+' '+x.album:(x as Work).category}`.toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/40)),currentPage=Math.min(page,pages),shown=filtered.slice((currentPage-1)*40,currentPage*40);const chosen=items.find(x=>x.id===editing);const activeItem=items.find(x=>x.id===active);
 const update=(id:string,key:string,value:unknown)=>setDraft(d=>({...d,[kind]:(d[kind] as Media[]).map(x=>x.id===id?{...x,[key]:value}:x)}));
 function end(e:DragEndEvent){setActive(null);if(!e.over||e.active.id===e.over.id)return;setDraft(d=>{const rows=d[kind] as Media[],a=rows.findIndex(x=>x.id===e.active.id),b=rows.findIndex(x=>x.id===e.over?.id);return a<0||b<0?d:{...d,[kind]:arrayMove(rows,a,b)}})}
 function move(id:string,direction:number){setDraft(d=>{const rows=d[kind] as Media[],a=rows.findIndex(x=>x.id===id),b=a+direction;return b<0||b>=rows.length?d:{...d,[kind]:arrayMove(rows,a,b)}})}
 function toggle(id:string){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 function addEmpty(){const id=crypto.randomUUID();const x=isMusic?{id,title:'New track',artist:'',album:'',playlist:group==='All'?'':group,playlists:group==='All'?[]:[group],url:'',cover:''}:{id,title:isFocus?'New media':'New film',category:group==='All'?(isFocus?'':'Fashion film'):group,year:String(new Date().getFullYear()),role:'Direction / Edit',description:'',poster:isFocus?'':draft.heroPoster,video:'',visible:true};setDraft(d=>({...d,[kind]:[...d[kind],x]}));setEditing(id);setQuery('');setPage(Math.ceil((items.length+1)/40))}
 async function batch(files:File[]){if(!files.length||working.current)return;working.current=true;setBusy(true);controller.current=new AbortController();const signal=controller.current.signal;const errors:{file:File;error:string}[]=[];let successes=0;setFailed([]);for(let i=0;i<files.length;i++){if(signal.aborted){files.slice(i).forEach(file=>errors.push({file,error:'업로드 중지됨'}));break}const file=files[i];setUploadState({done:i,total:files.length,percent:0,filename:file.name});try{const url=await uploadFile(file,p=>setUploadState({done:i,total:files.length,percent:p,filename:file.name}),signal);const isImage=!isMusic&&/^image\//.test(file.type);let poster=isImage?url:isFocus?'':draft.heroPoster;if(!isMusic&&!isImage){const cover=await videoPoster(file);if(cover&&!signal.aborted){try{poster=await uploadFile(cover,undefined,signal)}catch{}}}const id=crypto.randomUUID(),title=file.name.replace(/\.[^.]+$/,'');const entry=isMusic?{id,title,artist:'',album:'',playlist:group==='All'?'':group,playlists:group==='All'?[]:[group],url,cover:'',filename:file.name}:{id,title,category:group==='All'?(isFocus?'':'Fashion film'):group,year:String(new Date().getFullYear()),role:'Direction / Edit',description:'',poster,video:isImage?'':url,visible:true,filename:file.name};setDraft(d=>({...d,[kind]:[...d[kind],entry]}));if(i===0)setEditing(id);successes++}catch(e){errors.push({file,error:(e as Error).message})}}setFailed(errors);setUploadState(null);setBusy(false);working.current=false;notify(`${successes}개 업로드 완료${errors.length?` · ${errors.length}개 미완료`:''}. 저장 & 적용을 눌러 반영하세요.`);if(input.current)input.current.value=''}
 async function replace(file:File|undefined,key:string){if(!file||!chosen)return;try{setBusy(true);const url=await uploadFile(file);update(chosen.id,key,url);if(key==='url'||key==='video')update(chosen.id,'filename',file.name);notify('파일이 교체되었습니다. 저장 & 적용을 눌러 반영하세요.')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function addPlaylist(){const name=playlistName.trim();if(!name)return;setDraft(d=>({...d,musicPlaylists:[...new Set([...(d.musicPlaylists||[]),...d.tracks.flatMap(playlistsOf),name])]}));setPlaylistName('');setGroup(name);setPage(1)}
 function renamePlaylist(){if(group==='All')return;const name=prompt('새 플레이리스트 이름',group)?.trim();if(!name||name===group)return;setDraft(d=>({...d,musicPlaylists:[...new Set([...(d.musicPlaylists||[]).map(v=>v===group?name:v),name])],tracks:d.tracks.map(t=>membership(t,playlistsOf(t).map(v=>v===group?name:v)))}));setGroup(name)}
 function deletePlaylist(){if(group==='All'||!confirm(`“${group}” 플레이리스트를 삭제할까요? 음악 파일은 유지됩니다.`))return;setDraft(d=>({...d,musicPlaylists:(d.musicPlaylists||[]).filter(n=>n!==group),tracks:d.tracks.map(t=>membership(t,playlistsOf(t).filter(n=>n!==group)))}));setGroup('All')}
 function bulk(){setDraft(d=>({...d,[kind]:(d[kind] as Media[]).map(x=>{if(!selected.has(x.id))return x;if(isMusic){let t=x as Track;if(bulkArtist)t={...t,artist:bulkArtist};if(bulkAlbum)t={...t,album:bulkAlbum};if(bulkGroup)t=membership(t,[...playlistsOf(t),bulkGroup]);return t}return bulkGroup?{...x,category:bulkGroup}:x}),musicPlaylists:isMusic&&bulkGroup?[...new Set([...(d.musicPlaylists||[]),bulkGroup])]:d.musicPlaylists}));notify(`${selected.size}개 항목에 적용했습니다.`)}
 function removeFromPlaylist(){setDraft(d=>({...d,tracks:d.tracks.map(t=>selected.has(t.id)?membership(t,playlistsOf(t).filter(n=>n!==group)):t)}));notify(`${selected.size}개 항목을 ${group}에서 제외했습니다.`)}
 function remove(ids:Set<string>){if(!confirm(`${ids.size}개 항목을 목록에서 삭제할까요? 저장 전 변경 사항입니다.`))return;setDraft(d=>({...d,[kind]:d[kind].filter(x=>!ids.has(x.id))}));setSelected(new Set());if(editing&&ids.has(editing))setEditing(null)}
 const field=(key:string,label:string,multi=false)=><label className="field">{label}{multi?<textarea value={String((chosen as any)?.[key]||'')} onChange={e=>update(chosen!.id,key,e.target.value)}/>:<input value={String((chosen as any)?.[key]||'')} onChange={e=>update(chosen!.id,key,e.target.value)}/>}</label>;
 return <div className="media-library"><div className="library-toolbar"><div><h3>{isMusic?'Music library':isFocus?'In focus library':'Film library'} <span>{items.length}</span></h3><p>여러 파일을 함께 선택하세요 · 파일당 최대 100MB. 손잡이를 길게 눌러 순서를 바꾸세요.</p></div><div className="library-actions"><input hidden type="file" multiple ref={input} accept={isMusic?'audio/*,.mp3,.m4a,.wav,.ogg,.flac,.aac':isFocus?'image/jpeg,image/png,image/webp,video/mp4,video/webm,.mp4,.webm':'video/mp4,video/webm,.mp4,.webm'} onChange={e=>batch(Array.from(e.target.files||[]))}/><button className="upload-button" disabled={busy} onClick={()=>input.current?.click()}><Upload size={17}/>{isMusic?'음악 파일 업로드':isFocus?'사진·영상 업로드':'영상 파일 업로드'}</button><button className="secondary-button" disabled={busy} onClick={addEmpty}><Plus size={16}/>빈 항목 추가</button></div></div>
 {uploadState&&<section className="upload-progress"><div><span>{uploadState.done+1} / {uploadState.total} · {uploadState.filename}</span><button onClick={()=>controller.current?.abort()}>업로드 중지</button></div><Progress value={(uploadState.done+uploadState.percent/100)/uploadState.total*100}/><small>현재 파일 {uploadState.percent}% · 완료된 파일은 목록에 유지됩니다.</small></section>}
 {!!failed.length&&<section className="failed-uploads"><strong>{failed.length}개 파일 미완료</strong>{failed.slice(0,5).map((x,i)=><p key={i}>{x.file.name} · {x.error}</p>)}<button disabled={busy} onClick={()=>batch(failed.map(x=>x.file))}>미완료 파일 다시 업로드</button></section>}
 <div className="library-body"><aside className="library-groups"><button className={group==='All'?'selected':''} onClick={()=>{setGroup('All');setPage(1)}}>{isMusic?'전체 음악':isFocus?'전체 미디어':'전체 영상'}<span>{items.length}</span></button>{names.map(n=><button key={n} className={group===n?'selected':''} onClick={()=>{setGroup(n);setPage(1)}}>{n}<span>{items.filter(x=>isMusic?playlistsOf(x as Track).includes(n):(x as Work).category===n).length}</span></button>)}{isMusic&&<><div className="playlist-create"><input aria-label="새 플레이리스트 이름" placeholder="새 플레이리스트" value={playlistName} onChange={e=>setPlaylistName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addPlaylist()}/><button aria-label="플레이리스트 만들기" onClick={addPlaylist}><FolderPlus size={18}/></button></div>{group!=='All'&&<div className="playlist-actions"><button onClick={renamePlaylist}>이름 변경</button><button onClick={deletePlaylist}>삭제</button></div>}</>}</aside>
 <section className="library-list"><label className="library-search"><Search size={17}/><input placeholder={isMusic?'곡명·아티스트·앨범 검색':'작품명·분류 검색'} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><div className="selection-bar"><label><Checkbox checked={shown.length>0&&shown.every(x=>selected.has(x.id))} onCheckedChange={v=>setSelected(s=>{const n=new Set(s);shown.forEach(x=>v?n.add(x.id):n.delete(x.id));return n})}/> 이 페이지 선택</label><span>{selected.size}개 선택</span><button onClick={()=>setSelected(new Set(filtered.map(x=>x.id)))}>검색 결과 전체 선택</button></div>
 {!!selected.size&&<div className="bulk-edit">{isMusic&&<><input aria-label="일괄 아티스트" placeholder="아티스트 일괄 변경" value={bulkArtist} onChange={e=>setBulkArtist(e.target.value)}/><input aria-label="일괄 앨범" placeholder="앨범 일괄 변경" value={bulkAlbum} onChange={e=>setBulkAlbum(e.target.value)}/></>}<input aria-label={isMusic?'플레이리스트 추가':'분류 일괄 변경'} list={'groups-'+kind} placeholder={isMusic?'플레이리스트에 추가':'분류 일괄 변경'} value={bulkGroup} onChange={e=>setBulkGroup(e.target.value)}/><datalist id={'groups-'+kind}>{names.map(n=><option key={n} value={n}/>)}</datalist><div><button onClick={bulk}>선택 항목 적용</button>{isMusic&&group!=='All'&&<button onClick={removeFromPlaylist}>현재 플레이리스트에서 제외</button>}<button onClick={()=>remove(selected)}>선택 삭제</button><button onClick={()=>setSelected(new Set())}>선택 해제</button></div></div>}
 <DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={e=>setActive(String(e.active.id))} onDragEnd={end} onDragCancel={()=>setActive(null)}><SortableContext items={shown.map(x=>x.id)} strategy={verticalListSortingStrategy}><div className="media-rows">{shown.map(x=><SortRow key={x.id} item={x} index={items.findIndex(i=>i.id===x.id)} selected={selected.has(x.id)} active={editing===x.id} disabled={busy} onSelect={()=>toggle(x.id)} onEdit={()=>setEditing(x.id)}/>)}{!shown.length&&<p className="library-empty">{items.length?'해당 항목이 없습니다.':'파일을 업로드해 목록을 채워 주세요.'}</p>}</div></SortableContext><DragOverlay>{activeItem&&<div className="drag-overlay"><GripVertical size={20}/><strong>{activeItem.title}</strong></div>}</DragOverlay></DndContext>
 <Pagination className="library-pagination"><PaginationContent><PaginationItem><PaginationLink href="#" aria-label="이전 페이지" aria-disabled={currentPage===1} onClick={e=>{e.preventDefault();setPage(Math.max(1,currentPage-1))}}>‹</PaginationLink></PaginationItem><PaginationItem><span>{currentPage} / {pages} · {filtered.length}개</span></PaginationItem><PaginationItem><PaginationLink href="#" aria-label="다음 페이지" aria-disabled={currentPage===pages} onClick={e=>{e.preventDefault();setPage(Math.min(pages,currentPage+1))}}>›</PaginationLink></PaginationItem></PaginationContent></Pagination>
 </section><section className="library-detail">{chosen?<><div className="detail-heading"><h3>상세 편집</h3><div><button aria-label="위로 이동" onClick={()=>move(chosen.id,-1)}><ChevronUp size={17}/></button><button aria-label="아래로 이동" onClick={()=>move(chosen.id,1)}><ChevronDown size={17}/></button><button aria-label="항목 삭제" onClick={()=>remove(new Set([chosen.id]))}><Trash2 size={17}/></button></div></div>{field('title',isMusic?'곡명':'작품명')}{isMusic?<>{field('artist','아티스트')}{field('album','앨범')}<div className="field">플레이리스트<div className="playlist-membership">{names.map(n=><label key={n}><Checkbox checked={playlistsOf(chosen as Track).includes(n)} onCheckedChange={v=>setDraft(d=>({...d,tracks:d.tracks.map(t=>t.id===chosen.id?membership(t,v?[...playlistsOf(t),n]:playlistsOf(t).filter(p=>p!==n)):t)}))}/>{n}</label>)}{!names.length&&<p>왼쪽에서 플레이리스트를 먼저 만들어 주세요.</p>}</div></div><label className="field file-upload">음악 파일 교체<input disabled={busy} type="file" accept="audio/*" onChange={e=>replace(e.target.files?.[0],'url')}/><span className="uploaded-file">{(chosen as Track).filename||((chosen as Track).url?'등록된 음악':'파일 없음')}</span></label>{(chosen as Track).url&&<audio controls preload="none" src={(chosen as Track).url}/>}<label className="field file-upload">앨범 커버<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>replace(e.target.files?.[0],'cover')}/>{(chosen as Track).cover&&<img className="detail-cover" src={(chosen as Track).cover} alt="앨범 커버"/>}</label></>:<>{field('category','분류')}{field('year','연도')}{field('role','담당 역할')}{field('description','작품 설명',true)}<label className="toggle">공개 표시<Switch checked={(chosen as Work).visible} onCheckedChange={v=>update(chosen.id,'visible',v)}/></label><label className="field file-upload">영상 파일 교체<input disabled={busy} type="file" accept="video/mp4,video/webm" onChange={e=>replace(e.target.files?.[0],'video')}/></label>{isFocus&&!(chosen as Work).video&&(chosen as Work).poster&&<img className="detail-cover" src={(chosen as Work).poster} alt={(chosen as Work).title}/>} {(chosen as Work).video&&<video controls playsInline preload="none" poster={(chosen as Work).poster} src={(chosen as Work).video}/>}<label className="field file-upload">커버 이미지<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>replace(e.target.files?.[0],'poster')}/></label></>}</>:<p className="library-empty">목록에서 항목을 선택해 편집하세요.</p>}</section></div></div>
}
