import {Box3,Vector3,Group,LoadingManager,Mesh,MeshStandardMaterial,type Object3D,type AnimationClip,type Material,type Texture} from 'three';
import {unzipSync} from 'fflate';
const maxBytes=100*1024*1024;
const modelExtensions=/\.(glb|gltf|fbx|obj|stl|ply)$/i;
const whitePixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4////fwAJ+wP9KobjigAAAABJRU5ErkJggg==';
const normalize=(path:string)=>{let p=path;try{p=decodeURIComponent(p)}catch{}const parts:string[]=[];for(const part of p.replace(/\\/g,'/').split('/')){if(!part||part==='.')continue;if(part==='..')parts.pop();else parts.push(part)}return parts.join('/')};
export function unpackModel(bytes:Uint8Array){let expanded=0;const files=unzipSync(bytes,{filter:e=>{if(e.name.startsWith('__MACOSX/')||e.name.endsWith('/'))return false;expanded+=e.originalSize;if(expanded>160*1024*1024)throw Error('ZIP 내부 파일의 전체 크기는 최대 160MB입니다.');return true}});const candidates=Object.keys(files).filter(p=>modelExtensions.test(p));if(!candidates.length)throw Error('ZIP 안에 GLB·glTF·FBX·OBJ·STL·PLY 모델 파일이 없습니다.');const priority=(p:string)=>({glb:0,gltf:1,fbx:2,obj:3,stl:4,ply:5}[p.split('.').pop()!.toLowerCase()]??9);candidates.sort((a,b)=>priority(a)-priority(b)||a.split('/').length-b.split('/').length||a.localeCompare(b));return {files,name:candidates[0]};}
export function centerModel(object:Object3D){object.updateMatrixWorld(true);const box=new Box3().setFromObject(object);if(box.isEmpty()||![...box.min.toArray(),...box.max.toArray()].every(Number.isFinite))throw Error('표시할 수 있는 3D 표면이 없는 파일입니다.');const center=box.getCenter(new Vector3());const root=new Group();root.name='ICONIC_Centered_Model';root.add(object);root.position.copy(center).multiplyScalar(-1);root.updateMatrixWorld(true);return root;}
async function readyTextures(object:Object3D){const images=new Set<HTMLImageElement>();object.traverse(node=>{const mesh=node as Mesh;if(!mesh.isMesh)return;for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material]){for(const value of Object.values(m)){const t=value as Texture;if(t?.isTexture&&typeof HTMLImageElement!=='undefined'&&t.image instanceof HTMLImageElement)images.add(t.image)}}});await Promise.all([...images].map(img=>img.complete?(img.naturalWidth?Promise.resolve():Promise.reject(Error('텍스처를 읽을 수 없습니다. 모델과 텍스처를 ZIP으로 함께 올려 주세요.'))):new Promise<void>((resolve,reject)=>{img.addEventListener('load',()=>resolve(),{once:true});img.addEventListener('error',()=>reject(Error('텍스처를 읽을 수 없습니다. 모델과 텍스처를 ZIP으로 함께 올려 주세요.')),{once:true})})));}
function normalizeMaterials(object:Object3D){object.traverse(node=>{const mesh=node as Mesh;if(!mesh.isMesh)return;if(!mesh.geometry.getAttribute('normal'))mesh.geometry.computeVertexNormals();const convert=(m:Material)=>{if(m instanceof MeshStandardMaterial)return m;const source=m as Material&{color?:import('three').Color;map?:Texture;normalMap?:Texture;alphaMap?:Texture};const material=new MeshStandardMaterial({color:source.color?.clone()||0xdddddd,map:source.map,normalMap:source.normalMap,alphaMap:source.alphaMap,roughness:.5,metalness:.15,side:m.side,transparent:m.transparent,opacity:m.opacity,alphaTest:m.alphaTest});return material};mesh.material=Array.isArray(mesh.material)?mesh.material.map(convert):convert(mesh.material)});}
export async function prepareModel(file:File):Promise<File>{
 if(file.size>maxBytes)throw Error('3D 업로드 파일은 최대 100MB입니다.');if(/\.glb$/i.test(file.name))return file;
 let bytes:Uint8Array=new Uint8Array(await file.arrayBuffer());let name=file.name,files:Record<string,Uint8Array>={};const packaged=/\.zip$/i.test(name);if(packaged){const unpacked=unpackModel(bytes);files=unpacked.files;name=unpacked.name;bytes=files[name]}
 const ext=name.split('.').pop()?.toLowerCase();if(!modelExtensions.test(name))throw Error('GLB·glTF·FBX·OBJ·STL·PLY 또는 ZIP 파일을 선택해 주세요.');
 if(ext==='glb'){try{const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),json=JSON.parse(new TextDecoder().decode(bytes.subarray(20,20+view.getUint32(12,true))));if([...(json.buffers||[]),...(json.images||[])].every((x:{uri?:string})=>!x.uri||x.uri.startsWith('data:')))return new File([bytes.slice().buffer],name.split('/').pop()!,{type:'model/gltf-binary'})}catch{throw Error('올바른 GLB 2.0 파일이 아닙니다.')}}
 const urls:string[]=[],entries=Object.entries(files).map(([path,data])=>[normalize(path),data] as const);const directory=name.includes('/')?name.slice(0,name.lastIndexOf('/')+1):'';const manager=new LoadingManager();let resourcesPending=false,resourceError=false,finishResources:(()=>void)|undefined;manager.onStart=()=>{resourcesPending=true};manager.onLoad=()=>{resourcesPending=false;finishResources?.()};manager.onError=()=>{resourceError=true};
 manager.setURLModifier(url=>{if(/^(data:|blob:)/i.test(url))return url;const path=normalize(url),base=path.split('/').pop();const exact=entries.find(([key])=>key===path);const matches=entries.filter(([key])=>key.split('/').pop()===base);const entry=exact||(matches.length===1?matches[0]:undefined);if(entry){const ext=entry[0].split('.').pop()?.toLowerCase();const type=({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif'} as Record<string,string>)[ext||'']||'application/octet-stream';const objectUrl=URL.createObjectURL(new Blob([entry[1].slice().buffer],{type}));urls.push(objectUrl);return objectUrl}if(/\.(png|jpe?g|webp|gif|bmp|tga)$/i.test(path))return whitePixel;throw Error(`모델에 필요한 “${base||path}” 파일이 없습니다. 모델·데이터·텍스처를 ZIP 하나에 담아 업로드해 주세요.`)});
 try{
  let object:Object3D,animations:AnimationClip[]=[];const buffer=bytes.slice().buffer;
  if(ext==='gltf'||ext==='glb'){const {GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');const loader=new GLTFLoader(manager);const gltf=await loader.parseAsync(ext==='gltf'?new TextDecoder().decode(bytes):buffer,directory);object=gltf.scene;animations=gltf.animations}
  else if(ext==='fbx'){const {FBXLoader}=await import('three/addons/loaders/FBXLoader.js');object=new FBXLoader(manager).parse(buffer,directory);animations=object.animations}
  else if(ext==='obj'){const {OBJLoader}=await import('three/addons/loaders/OBJLoader.js');const loader=new OBJLoader(manager),text=new TextDecoder().decode(bytes);const declared=text.match(/^mtllib\s+(.+)$/m)?.[1]?.trim();const mtl=declared?entries.find(([p])=>p===normalize(directory+declared)||p.split('/').pop()===declared):entries.find(([p])=>p.toLowerCase()===name.replace(/\.obj$/i,'.mtl').toLowerCase());if(mtl){const {MTLLoader}=await import('three/addons/loaders/MTLLoader.js');const materials=new MTLLoader(manager).parse(new TextDecoder().decode(mtl[1]),mtl[0].includes('/')?mtl[0].slice(0,mtl[0].lastIndexOf('/')+1):directory);materials.preload();loader.setMaterials(materials)}object=loader.parse(text)}
  else {const geometry=ext==='stl'?new (await import('three/addons/loaders/STLLoader.js')).STLLoader().parse(buffer):new (await import('three/addons/loaders/PLYLoader.js')).PLYLoader().parse(buffer);geometry.computeVertexNormals();object=new Mesh(geometry,new MeshStandardMaterial({color:0xdddddd,vertexColors:!!geometry.getAttribute('color'),metalness:.15,roughness:.5}));object.name='ICONIC_Logo'}
  if(resourcesPending)await new Promise<void>(resolve=>{finishResources=resolve});if(resourceError)throw Error('텍스처를 읽을 수 없습니다. 모델과 텍스처를 ZIP으로 함께 올려 주세요.');await readyTextures(object);normalizeMaterials(object);const centered=centerModel(object);const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const result=await new GLTFExporter().parseAsync(centered,{binary:true,animations,onlyVisible:true,maxTextureSize:4096});if(!(result instanceof ArrayBuffer))throw Error('GLB 변환에 실패했습니다.');if(result.byteLength>maxBytes)throw Error('변환된 GLB가 100MB를 넘습니다. 모델이나 텍스처 크기를 줄여 주세요.');return new File([result],name.split('/').pop()!.replace(/\.[^.]+$/,'.glb'),{type:'model/gltf-binary'});
 }catch(e){if(e instanceof Error&&/ZIP|100MB|160MB|텍스처|표면|GLB/.test(e.message))throw e;throw Error('이 모델을 변환하지 못했습니다. 압축 모델이나 전용 효과가 있는 파일은 텍스처 포함 GLB로 내보내거나 원본 자료를 ZIP으로 묶어 주세요.')}finally{urls.forEach(url=>URL.revokeObjectURL(url))}
}
