'use client';
import {useEffect,useRef,useState,type CSSProperties,type Dispatch,type PointerEvent,type SetStateAction} from 'react';
import {ArrowDown,ArrowUp,Copy,Eye,EyeOff,Grip,Layers3,Maximize2,PanelLeft,PanelRight,Plus,RotateCcw,Save,Settings2,SlidersHorizontal,Trash2,Type,X} from 'lucide-react';
import type {Config,NavItemKey,SiteSectionKey,Work} from './defaults';
import {uploadFile} from './media-upload';

type SectionKey=SiteSectionKey;
type PanelTab='layers'|'content'|'layout'|'style';
type Point={x:number;y:number};
type TextStyleKey=keyof Config['textStyles'];
type TextPatch=Partial<{font:string;size:number;color:string;align:'left'|'center'|'right';x:number;y:number;letterSpacing:number;weight:number;opacity:number;textTransform:'none'|'uppercase'|'lowercase'|'capitalize'}>;
export type VisualSelection=SectionKey|`work:${string}`;

const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n));
const sectionDefs:{key:SectionKey;label:string}[]=[
 {key:'nav',label:'Header'},{key:'hero',label:'Main visual'},{key:'work',label:'Work'},
 {key:'about',label:'About'},{key:'team',label:'Team'},{key:'footer',label:'Footer'}
];
const navLabels:Record<NavItemKey,string>={work:'Work',about:'About',team:'Team',contact:'Contact'};
const labelKeys:Record<NavItemKey,'navWorkLabel'|'navAboutLabel'|'navTeamLabel'|'navContactLabel'>={work:'navWorkLabel',about:'navAboutLabel',team:'navTeamLabel',contact:'navContactLabel'};
const pointFromStorage=(key:string):Point|null=>{
 try{if(typeof window==='undefined')return null;const raw=localStorage.getItem(key);if(!raw)return null;const p=JSON.parse(raw);return Number.isFinite(p?.x)&&Number.isFinite(p?.y)?p:null}catch{return null}
};

export default function VisualSiteEditor({
 config,setConfig,selection,setSelection,onSave,onCancel,onOpenAdmin,busy
}:{
 config:Config;setConfig:Dispatch<SetStateAction<Config>>;selection:VisualSelection;setSelection:(value:VisualSelection)=>void;
 onSave:()=>void|Promise<void>;onCancel:()=>void;onOpenAdmin:()=>void;busy:boolean;
}){
 const [rect,setRect]=useState<DOMRect|null>(null),[uploading,setUploading]=useState(false),[panelSide,setPanelSide]=useState<'left'|'right'>('right'),[panelOpen,setPanelOpen]=useState(true),[tab,setTab]=useState<PanelTab>('layers');
 const [toolbarPos,setToolbarPos]=useState<Point|null>(()=>pointFromStorage('viivii-visual-toolbar-pos'));
 const [panelPos,setPanelPos]=useState<Point|null>(()=>pointFromStorage('viivii-visual-panel-pos'));
 const dragState=useRef<{x:number;y:number;baseX:number;baseY:number}|null>(null),resizeState=useRef<{x:number;y:number;base:number}|null>(null);
 const selectedWorkId=selection.startsWith('work:')?selection.slice(5):'';
 const selectedWork=selectedWorkId?config.works.find(w=>w.id===selectedWorkId)||null:null;
 const sectionSelection=(selection.startsWith('work:')?'work':selection) as SectionKey;

 const targetFor=(value:VisualSelection=selection)=>{
  if(typeof document==='undefined')return null;
  if(value.startsWith('work:')){const id=value.slice(5);return Array.from(document.querySelectorAll<HTMLElement>('[data-visual-work-id]')).find(el=>el.dataset.visualWorkId===id)||null}
  return document.querySelector<HTMLElement>(`[data-visual-section="${value}"]`);
 };
 const refresh=()=>{const el=targetFor();setRect(el?el.getBoundingClientRect():null)};
 useEffect(()=>{let raf=0;const sync=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(refresh)};sync();window.addEventListener('scroll',sync,{passive:true});window.addEventListener('resize',sync);return()=>{cancelAnimationFrame(raf);window.removeEventListener('scroll',sync);window.removeEventListener('resize',sync)}},[selection,config]);
 useEffect(()=>{if(panelPos)return;const el=targetFor();if(!el)return;const r=el.getBoundingClientRect();if(r.width<window.innerWidth*.76)setPanelSide(r.left+r.width/2>window.innerWidth/2?'left':'right');else if(selection==='nav')setPanelSide('right')},[selection,panelPos]);

 const patch=<K extends keyof Config>(key:K,value:Config[K])=>setConfig(d=>({...d,[key]:value}));
 const patchTextStyle=(key:TextStyleKey,value:TextPatch)=>setConfig(d=>({...d,textStyles:{...d.textStyles,[key]:{...d.textStyles[key],...value}}}));
 const patchWork=(id:string,key:keyof Work,value:Work[keyof Work])=>setConfig(d=>({...d,works:d.works.map(w=>w.id===id?{...w,[key]:value}:w)}));
 const patchTeam=(id:string,key:string,value:unknown)=>setConfig(d=>({...d,teamMembers:d.teamMembers.map(m=>m.id===id?{...m,[key]:value}:m)}));
 const layoutKeys=(key:SectionKey)=>{
  if(key==='nav')return {x:'navOffsetX',y:'navOffsetY',scale:'navScale'} as const;
  if(key==='hero')return {x:'heroOffsetX',y:'heroOffsetY',scale:'heroScale'} as const;
  if(key==='work')return {x:'workOffsetX',y:'workOffsetY',scale:'workScale'} as const;
  if(key==='about')return {x:'aboutOffsetX',y:'aboutOffsetY',scale:'aboutScale'} as const;
  if(key==='team')return {x:'teamOffsetX',y:'teamOffsetY',scale:'teamScale'} as const;
  if(key==='footer')return {x:'footerOffsetX',y:'footerOffsetY',scale:'footerScale'} as const;
  return null;
 };
 const meta=layoutKeys(sectionSelection);

 const beginMove=(e:PointerEvent<HTMLButtonElement>)=>{
  if(!meta||selectedWork)return;e.preventDefault();e.stopPropagation();
  dragState.current={x:e.clientX,y:e.clientY,baseX:Number(config[meta.x]),baseY:Number(config[meta.y])};
  const move=(event:globalThis.PointerEvent)=>{const start=dragState.current;if(!start)return;setConfig(d=>({...d,[meta.x]:clamp(Math.round(start.baseX+event.clientX-start.x),-500,500),[meta.y]:clamp(Math.round(start.baseY+event.clientY-start.y),-500,500)}))};
  const up=()=>{dragState.current=null;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);refresh()};
  window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});
 };
 const beginResize=(e:PointerEvent<HTMLButtonElement>)=>{
  if(!meta||selectedWork)return;e.preventDefault();e.stopPropagation();
  resizeState.current={x:e.clientX,y:e.clientY,base:Number(config[meta.scale])};
  const move=(event:globalThis.PointerEvent)=>{const start=resizeState.current;if(!start)return;const delta=((event.clientX-start.x)+(event.clientY-start.y))/720;setConfig(d=>({...d,[meta.scale]:Math.round(clamp(start.base+delta,.65,1.45)*100)/100}))};
  const up=()=>{resizeState.current=null;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);refresh()};
  window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});
 };
 const beginChromeDrag=(e:PointerEvent<HTMLElement>,kind:'toolbar'|'panel')=>{
  if(e.button!==0)return;
  const selector=kind==='toolbar'?'.visual-editor-topbar':'.visual-editor-panel';
  const node=(e.currentTarget as HTMLElement).closest<HTMLElement>(selector);if(!node)return;
  e.preventDefault();
  const r=node.getBoundingClientRect(),sx=e.clientX,sy=e.clientY;
  const setPos=kind==='toolbar'?setToolbarPos:setPanelPos;
  const storageKey=kind==='toolbar'?'viivii-visual-toolbar-pos':'viivii-visual-panel-pos';
  const move=(ev:globalThis.PointerEvent)=>{
   const x=clamp(r.left+ev.clientX-sx,8,Math.max(8,window.innerWidth-r.width-8));
   const y=clamp(r.top+ev.clientY-sy,8,Math.max(8,window.innerHeight-r.height-8));
   setPos({x:Math.round(x),y:Math.round(y)});
  };
  const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);requestAnimationFrame(()=>{const el=document.querySelector<HTMLElement>(selector);if(!el)return;const rr=el.getBoundingClientRect();const p={x:Math.round(rr.left),y:Math.round(rr.top)};setPos(p);try{localStorage.setItem(storageKey,JSON.stringify(p))}catch{}})};
  window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});
 };
 const resetChrome=(kind:'toolbar'|'panel')=>{if(kind==='toolbar'){setToolbarPos(null);try{localStorage.removeItem('viivii-visual-toolbar-pos')}catch{}}else{setPanelPos(null);try{localStorage.removeItem('viivii-visual-panel-pos')}catch{}}};

 const isVisible=(key:SectionKey)=>key==='nav'?config.showNav:key==='hero'?config.showHero:key==='footer'?config.showFooter:key==='work'?config.navOrder.includes('work'):key==='about'?config.showAbout&&config.navOrder.includes('about'):config.showTeam&&config.navOrder.includes('team');
 const removeSection=(key:SectionKey)=>setConfig(d=>key==='nav'?{...d,showNav:false}:key==='hero'?{...d,showHero:false}:key==='footer'?{...d,showFooter:false}:key==='work'?{...d,navOrder:d.navOrder.filter(x=>x!=='work')}:key==='about'?{...d,showAbout:false,navOrder:d.navOrder.filter(x=>x!=='about')}:{...d,showTeam:false,navOrder:d.navOrder.filter(x=>x!=='team')});
 const restoreSection=(key:SectionKey)=>setConfig(d=>key==='nav'?{...d,showNav:true}:key==='hero'?{...d,showHero:true}:key==='footer'?{...d,showFooter:true}:key==='work'?{...d,navOrder:d.navOrder.includes('work')?d.navOrder:[...d.navOrder,'work']}:key==='about'?{...d,showAbout:true,navOrder:d.navOrder.includes('about')?d.navOrder:[...d.navOrder,'about']}:{...d,showTeam:true,navOrder:d.navOrder.includes('team')?d.navOrder:[...d.navOrder,'team']});
 const resetLayout=()=>{if(meta)setConfig(d=>({...d,[meta.x]:0,[meta.y]:0,[meta.scale]:1}))};
 const reorderMenu=(item:NavItemKey,dir:number)=>setConfig(d=>{const arr=[...d.navOrder],i=arr.indexOf(item),j=i+dir;if(i<0||j<0||j>=arr.length)return d;[arr[i],arr[j]]=[arr[j],arr[i]];return {...d,navOrder:arr}});
 const removeMenu=(item:NavItemKey)=>setConfig(d=>({...d,navOrder:d.navOrder.filter(x=>x!==item)}));
 const restoreMenu=(item:NavItemKey)=>setConfig(d=>d.navOrder.includes(item)?d:{...d,navOrder:[...d.navOrder,item]});
 const reorderSection=(from:SectionKey,to:SectionKey)=>setConfig(d=>{if(from===to)return d;const arr=[...(d.sectionOrder||sectionDefs.map(s=>s.key))],a=arr.indexOf(from),b=arr.indexOf(to);if(a<0||b<0)return d;arr.splice(a,1);arr.splice(b,0,from);return {...d,sectionOrder:arr}});
 const moveWork=(id:string,dir:number)=>setConfig(d=>{const arr=[...d.works],i=arr.findIndex(w=>w.id===id),j=i+dir;if(i<0||j<0||j>=arr.length)return d;[arr[i],arr[j]]=[arr[j],arr[i]];return {...d,works:arr}});
 const reorderWork=(from:string,to:string)=>setConfig(d=>{if(from===to)return d;const arr=[...d.works],a=arr.findIndex(w=>w.id===from),b=arr.findIndex(w=>w.id===to);if(a<0||b<0)return d;const [item]=arr.splice(a,1);arr.splice(b,0,item);return {...d,works:arr}});
 const addWork=()=>{const id='visual-'+Date.now(),work:Work={id,title:'New work',category:'Unassigned',year:new Date().getFullYear().toString(),role:'',description:'',poster:'',video:'',visible:false};setConfig(d=>({...d,works:[...d.works,work]}));setSelection(`work:${id}`);setTab('content')};
 const duplicateWork=(work:Work)=>{const copy={...work,id:'visual-'+Date.now(),title:work.title+' copy'};setConfig(d=>({...d,works:[...d.works,copy]}));setSelection(`work:${copy.id}`);setTab('content')};
 const deleteWork=(id:string)=>{setConfig(d=>({...d,works:d.works.filter(w=>w.id!==id)}));setSelection('work');setTab('layers')};
 const uploadWork=async(file:File|undefined,field:'poster'|'video')=>{if(!file||!selectedWork)return;try{setUploading(true);const url=await uploadFile(file);setConfig(d=>({...d,works:d.works.map(w=>w.id===selectedWork.id?{...w,[field]:url,visible:true}:w)}))}finally{setUploading(false)}};
 const uploadConfig=async(file:File|undefined,key:keyof Config)=>{if(!file)return;try{setUploading(true);const url=await uploadFile(file);setConfig(d=>({...d,[key]:url,...(key==='aboutImage'?{aboutMediaType:'image'}:{})}))}finally{setUploading(false)}};
 const selectLayer=(value:VisualSelection)=>{setSelection(value);requestAnimationFrame(()=>targetFor(value)?.scrollIntoView({behavior:'smooth',block:value==='nav'?'start':'center'}))};
 const hiddenSections=sectionDefs.filter(s=>!isVisible(s.key)),toolbarBottom=!toolbarPos&&!!rect&&rect.top<112&&window.innerWidth>820,labelInside=!!rect&&rect.top<28;
 const toolbarStyle=toolbarPos?{'--ve-toolbar-x':toolbarPos.x+'px','--ve-toolbar-y':toolbarPos.y+'px'} as CSSProperties:undefined;
 const panelStyle=panelPos?{'--ve-panel-x':panelPos.x+'px','--ve-panel-y':panelPos.y+'px'} as CSSProperties:undefined;

 return <div className={'visual-editor-ui is-panel-'+panelSide} data-visual-editor="true">
  <div style={toolbarStyle} className={'visual-editor-topbar '+(toolbarPos?'is-free ':toolbarBottom?'is-bottom ':'is-top ')}>
   <div className="visual-editor-title visual-editor-drag-zone" onPointerDown={e=>beginChromeDrag(e,'toolbar')} onDoubleClick={()=>resetChrome('toolbar')}><Grip size={14}/><Settings2 size={16}/><strong>VISUAL EDIT</strong><span>드래그 이동 · 화면에서 선택 · 크기 · 콘텐츠 · 스타일</span></div>
   <div className="visual-editor-toolbar-tools">
    <button type="button" className="visual-toolbar-icon" title="패널 위치 전환" onClick={()=>{setPanelPos(null);setPanelSide(v=>v==='right'?'left':'right')}}>{panelSide==='right'?<PanelLeft size={15}/>:<PanelRight size={15}/>}</button>
    <button type="button" className="visual-toolbar-icon" title={panelOpen?'패널 접기':'패널 열기'} onClick={()=>setPanelOpen(v=>!v)}><SlidersHorizontal size={15}/></button>
    <div className="visual-editor-actions"><button type="button" onClick={onOpenAdmin}>ADMIN</button><button type="button" onClick={onCancel}><X size={15}/><span>취소</span></button><button type="button" className="is-primary" disabled={busy} onClick={onSave}><Save size={15}/><span>{busy?'저장 중':'저장'}</span></button></div>
   </div>
  </div>

  {panelOpen?<aside style={panelStyle} className={'visual-editor-panel is-'+panelSide+(panelPos?' is-free':'')}>
   <div className="visual-panel-head"><div className="visual-panel-drag-zone" onPointerDown={e=>beginChromeDrag(e,'panel')} onDoubleClick={()=>resetChrome('panel')}><Grip size={13}/><span><strong>{selectedWork?'Work card':sectionDefs.find(s=>s.key===sectionSelection)?.label}</strong><small>{selectedWork?'카드 단위 편집':'끌어서 패널 이동 · 더블클릭 위치 초기화'}</small></span></div><button type="button" aria-label="편집 패널 접기" onClick={()=>setPanelOpen(false)}><X size={15}/></button></div>
   <div className="visual-editor-tabs" role="tablist"><button className={tab==='layers'?'is-active':''} onClick={()=>setTab('layers')}><Layers3 size={13}/>Layers</button><button className={tab==='content'?'is-active':''} onClick={()=>setTab('content')}><Type size={13}/>Content</button><button className={tab==='layout'?'is-active':''} onClick={()=>setTab('layout')}><Maximize2 size={13}/>Layout</button><button className={tab==='style'?'is-active':''} onClick={()=>setTab('style')}><SlidersHorizontal size={13}/>Style</button></div>
   {tab==='layers'&&<LayersPanel config={config} selection={selection} select={selectLayer} isVisible={isVisible} hide={removeSection} restore={restoreSection} reorderSection={reorderSection} moveWork={moveWork} reorderWork={reorderWork} patchWork={patchWork} deleteWork={deleteWork} addWork={addWork}/>}
   {tab==='content'&&<div className="visual-editor-context">{selectedWork?<WorkEditor work={selectedWork} patch={(key,value)=>patchWork(selectedWork.id,key,value)} onUpload={uploadWork} uploading={uploading} onDuplicate={()=>duplicateWork(selectedWork)} onDelete={()=>deleteWork(selectedWork.id)}/>:<SectionEditor section={sectionSelection} config={config} patch={patch} patchTeam={patchTeam} reorder={reorderMenu} removeMenu={removeMenu} restoreMenu={restoreMenu} addWork={addWork} uploadConfig={uploadConfig} uploading={uploading}/>}</div>}
   {tab==='layout'&&<div className="visual-editor-layout"><div className="visual-editor-panel-head"><strong>Geometry</strong>{meta&&<button type="button" onClick={resetLayout}><RotateCcw size={13}/>Reset</button>}</div>{meta&&<><Range label="X position" value={Number(config[meta.x])} min={-500} max={500} step={1} suffix="px" onChange={v=>patch(meta.x,v as never)}/><Range label="Y position" value={Number(config[meta.y])} min={-500} max={500} step={1} suffix="px" onChange={v=>patch(meta.y,v as never)}/><Range label="Scale" value={Math.round(Number(config[meta.scale])*100)} min={65} max={145} step={1} suffix="%" onChange={v=>patch(meta.scale,(v/100) as never)}/></>}{sectionSelection==='work'&&<Range label="Grid columns" value={config.columns} min={1} max={4} step={1} onChange={v=>patch('columns',v)}/>} {sectionSelection==='team'&&<><Range label="Media size" value={config.teamMediaSize} min={120} max={520} step={1} suffix="px" onChange={v=>patch('teamMediaSize',v)}/><Range label="Row gap" value={config.teamRowGap} min={12} max={180} step={1} suffix="px" onChange={v=>patch('teamRowGap',v)}/></>}<Range label="Global section spacing" value={config.spacing} min={28} max={180} step={1} suffix="px" onChange={v=>patch('spacing',v)}/>{!selectedWork&&<button type="button" className="visual-editor-danger" onClick={()=>removeSection(sectionSelection)}><EyeOff size={14}/> 이 영역 숨기기</button>}</div>}
   {tab==='style'&&<StylePanel section={sectionSelection} config={config} patch={patch} patchTextStyle={patchTextStyle} uploadConfig={uploadConfig} uploading={uploading}/>}
   {hiddenSections.length>0&&<div className="visual-editor-restore"><span>숨긴 영역</span><div>{hiddenSections.map(s=><button type="button" key={s.key} onClick={()=>{restoreSection(s.key);selectLayer(s.key)}}><Plus size={13}/>{s.label}</button>)}</div></div>}
  </aside>:<button type="button" className={'visual-panel-reopen is-'+panelSide} onClick={()=>setPanelOpen(true)}><SlidersHorizontal size={16}/><span>편집 패널</span></button>}

  {rect&&<div className={'visual-selection-frame is-panel-'+panelSide+(labelInside?' is-label-inside':'')} style={{left:rect.left,top:rect.top,width:rect.width,height:rect.height}}><span className="visual-selection-label">{selectedWork?'WORK CARD':sectionDefs.find(s=>s.key===sectionSelection)?.label}</span>{meta&&!selectedWork&&<button type="button" className="visual-move-handle" aria-label="영역 이동" onPointerDown={beginMove}><Grip size={16}/></button>}{meta&&!selectedWork&&<button type="button" className="visual-resize-handle" aria-label="영역 크기 조절" onPointerDown={beginResize}><Maximize2 size={15}/></button>}</div>}
 </div>;
}

function LayersPanel({config,selection,select,isVisible,hide,restore,reorderSection,moveWork,reorderWork,patchWork,deleteWork,addWork}:{config:Config;selection:VisualSelection;select:(v:VisualSelection)=>void;isVisible:(k:SectionKey)=>boolean;hide:(k:SectionKey)=>void;restore:(k:SectionKey)=>void;reorderSection:(from:SectionKey,to:SectionKey)=>void;moveWork:(id:string,dir:number)=>void;reorderWork:(from:string,to:string)=>void;patchWork:(id:string,key:keyof Work,value:Work[keyof Work])=>void;deleteWork:(id:string)=>void;addWork:()=>void}){
 const [dragSection,setDragSection]=useState<SectionKey|null>(null),[dragWork,setDragWork]=useState<string|null>(null);
 const ordered=(config.sectionOrder||sectionDefs.map(s=>s.key)).map(key=>sectionDefs.find(s=>s.key===key)).filter(Boolean) as typeof sectionDefs;
 return <div className="visual-layers"><div className="visual-layer-heading"><span>Page layers · 드래그로 실제 페이지 순서 변경</span><button onClick={addWork}><Plus size={13}/>작품</button></div>{ordered.map(section=><div className={'visual-layer-group '+(dragSection===section.key?'is-dragging':'')} key={section.key} onDragOver={e=>{if(dragSection)e.preventDefault()}} onDrop={e=>{if(dragSection){e.preventDefault();reorderSection(dragSection,section.key);setDragSection(null)}}}><div className={'visual-layer-row '+(selection===section.key?'is-active':'')}><button type="button" draggable className="visual-layer-grip" title="드래그해서 섹션 순서 이동" onDragStart={e=>{setDragSection(section.key);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',section.key)}} onDragEnd={()=>setDragSection(null)}><Grip size={13}/></button><button className="visual-layer-select" onClick={()=>select(section.key)}><span>{section.label}</span><small>{isVisible(section.key)?'VISIBLE':'HIDDEN'}</small></button><button className="visual-layer-icon" aria-label={isVisible(section.key)?'숨기기':'표시하기'} onClick={()=>isVisible(section.key)?hide(section.key):restore(section.key)}>{isVisible(section.key)?<Eye size={14}/>:<EyeOff size={14}/>}</button></div>{section.key==='work'&&<div className="visual-layer-children">{config.works.map((work,index)=><div className={'visual-layer-row is-child '+(selection===`work:${work.id}`?'is-active':'')+(dragWork===work.id?' is-dragging':'')} key={work.id} onDragOver={e=>{if(dragWork){e.preventDefault();e.stopPropagation()}}} onDrop={e=>{if(dragWork){e.preventDefault();e.stopPropagation();reorderWork(dragWork,work.id);setDragWork(null)}}}><button type="button" draggable className="visual-layer-grip" title="드래그해서 작품 순서 이동" onDragStart={e=>{e.stopPropagation();setDragWork(work.id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',work.id)}} onDragEnd={()=>setDragWork(null)}><Grip size={12}/></button><button className="visual-layer-select" onClick={()=>select(`work:${work.id}`)}><span>{work.title||'Untitled'}</span><small>{work.visible?'LIVE':'DRAFT'}</small></button><div className="visual-layer-mini-actions"><button disabled={index===0} onClick={()=>moveWork(work.id,-1)}><ArrowUp size={12}/></button><button disabled={index===config.works.length-1} onClick={()=>moveWork(work.id,1)}><ArrowDown size={12}/></button><button onClick={()=>patchWork(work.id,'visible',!work.visible)}>{work.visible?<Eye size={12}/>:<EyeOff size={12}/>}</button><button className="is-danger" onClick={()=>deleteWork(work.id)}><Trash2 size={12}/></button></div></div>)}</div>}</div>)}</div>;
}
function Range({label,value,min,max,step,suffix='',onChange}:{label:string;value:number;min:number;max:number;step:number;suffix?:string;onChange:(v:number)=>void}){return <label className="visual-range"><span>{label}<b>{Math.round(value*100)/100}{suffix}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>}
function TextField({label,value,onChange,multi=false}:{label:string;value:string;onChange:(v:string)=>void;multi?:boolean}){return <label className="visual-field"><span>{label}</span>{multi?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function FileField({label,accept,disabled,value,onFile,onClear}:{label:string;accept:string;disabled:boolean;value?:string;onFile:(file:File|undefined)=>void;onClear?:()=>void}){return <label className="visual-upload"><span>{label}</span><input type="file" accept={accept} disabled={disabled} onChange={e=>onFile(e.target.files?.[0])}/>{value&&<span className="visual-upload-state">등록됨 {onClear&&<button type="button" onClick={e=>{e.preventDefault();onClear()}}>제거</button>}</span>}</label>}

function SectionEditor({section,config,patch,patchTeam,reorder,removeMenu,restoreMenu,addWork,uploadConfig,uploading}:{section:SectionKey;config:Config;patch:<K extends keyof Config>(key:K,value:Config[K])=>void;patchTeam:(id:string,key:string,value:unknown)=>void;reorder:(item:NavItemKey,dir:number)=>void;removeMenu:(item:NavItemKey)=>void;restoreMenu:(item:NavItemKey)=>void;addWork:()=>void;uploadConfig:(file:File|undefined,key:keyof Config)=>void;uploading:boolean}){
 const missing=(['work','about','team','contact'] as NavItemKey[]).filter(x=>!config.navOrder.includes(x));
 if(section==='nav')return <><h3>Header</h3><TextField label="브랜드 이름" value={config.name} onChange={v=>patch('name',v)}/><FileField label="상단 로고" accept="image/*" disabled={uploading} value={config.logo} onFile={f=>uploadConfig(f,'logo')} onClear={()=>patch('logo','')}/><Range label="Glass opacity" value={config.navOpacity} min={0} max={100} step={1} suffix="%" onChange={v=>patch('navOpacity',v)}/><div className="visual-menu-order"><span>Menu order & labels</span>{config.navOrder.map((item,index)=><div key={item}><input value={String(config[labelKeys[item]])} onChange={e=>patch(labelKeys[item],e.target.value)}/><div><button disabled={index===0} onClick={()=>reorder(item,-1)}><ArrowUp size={13}/></button><button disabled={index===config.navOrder.length-1} onClick={()=>reorder(item,1)}><ArrowDown size={13}/></button><button className="is-danger" onClick={()=>removeMenu(item)}><Trash2 size={13}/></button></div></div>)}{missing.length>0&&<div className="visual-menu-restore">{missing.map(item=><button key={item} onClick={()=>restoreMenu(item)}><Plus size={12}/>{navLabels[item]}</button>)}</div>}</div></>;
 if(section==='hero')return <><h3>Main visual</h3><TextField label="Hover title" value={config.heroCaption} onChange={v=>patch('heroCaption',v)}/><TextField label="Eyebrow" value={config.eyebrow} onChange={v=>patch('eyebrow',v)}/><TextField label="Bottom copy" value={config.subtitle} onChange={v=>patch('subtitle',v)}/><FileField label="Main video" accept="video/mp4,video/webm" disabled={uploading} value={config.heroVideo} onFile={f=>uploadConfig(f,'heroVideo')} onClear={()=>patch('heroVideo','')}/><FileField label="Fallback image" accept="image/jpeg,image/png,image/webp" disabled={uploading} value={config.heroPoster} onFile={f=>uploadConfig(f,'heroPoster')} onClear={()=>patch('heroPoster','')}/><label className="visual-toggle"><span>자동 재생</span><input type="checkbox" checked={config.autoplay} onChange={e=>patch('autoplay',e.target.checked)}/></label></>;
 if(section==='work')return <><div className="visual-editor-panel-head"><h3>Work</h3><button type="button" onClick={addWork}><Plus size={13}/>작품 추가</button></div><TextField label="Small title" value={config.workKicker} onChange={v=>patch('workKicker',v)}/><TextField label="Headline" value={config.headline} multi onChange={v=>patch('headline',v)}/><TextField label="Aside" value={config.workAside} multi onChange={v=>patch('workAside',v)}/><Range label="Columns" value={config.columns} min={1} max={4} step={1} onChange={v=>patch('columns',v)}/><Range label="전체화면 배경 불투명도" value={config.filmBackdropOpacity} min={0} max={100} step={1} suffix="%" onChange={v=>patch('filmBackdropOpacity',v)}/><Range label="전체화면 배경 블러" value={config.filmBackdropBlur} min={0} max={60} step={1} suffix="px" onChange={v=>patch('filmBackdropBlur',v)}/></>;
 if(section==='about')return <><h3>About</h3><TextField label="Small title" value={config.aboutKicker} onChange={v=>patch('aboutKicker',v)}/><TextField label="Headline" value={config.aboutHeadline} multi onChange={v=>patch('aboutHeadline',v)}/><TextField label="Body" value={config.about} multi onChange={v=>patch('about',v)}/><TextField label="Disciplines" value={config.aboutDisciplines} multi onChange={v=>patch('aboutDisciplines',v)}/><label className="visual-field"><span>Visual type</span><select value={config.aboutMediaType} onChange={e=>patch('aboutMediaType',e.target.value)}><option value="image">Image</option><option value="3d">3D</option></select></label>{config.aboutMediaType==='image'?<FileField label="About image" accept="image/jpeg,image/png,image/webp" disabled={uploading} value={config.aboutImage} onFile={f=>uploadConfig(f,'aboutImage')} onClear={()=>patch('aboutImage','')}/>:<FileField label="3D model" accept=".glb,.gltf,.fbx,.obj,.stl,.ply,.zip" disabled={uploading} value={config.aboutModel} onFile={f=>uploadConfig(f,'aboutModel')} onClear={()=>patch('aboutModel','')}/>}</>;
 if(section==='team')return <><h3>Team</h3><TextField label="Small title" value={config.teamKicker} onChange={v=>patch('teamKicker',v)}/><TextField label="Headline" value={config.teamHeadline} multi onChange={v=>patch('teamHeadline',v)}/><div className="visual-team-list">{config.teamMembers.map(m=><div className="visual-team-row" key={m.id}><input value={m.name} placeholder="Name" onChange={e=>patchTeam(m.id,'name',e.target.value)}/><input value={m.codeName} placeholder="CODE" onChange={e=>patchTeam(m.id,'codeName',e.target.value)}/><label><span>표시</span><input type="checkbox" checked={m.visible} onChange={e=>patchTeam(m.id,'visible',e.target.checked)}/></label></div>)}</div></>;
 return <><h3>Footer</h3><TextField label="Admin label" value={config.footerAdminLabel} onChange={v=>patch('footerAdminLabel',v)}/><TextField label="Contact email" value={config.email} onChange={v=>patch('email',v)}/><TextField label="Instagram" value={config.instagram} onChange={v=>patch('instagram',v)}/><label className="visual-toggle"><span>음악 플레이어 표시</span><input type="checkbox" checked={config.showMusic} onChange={e=>patch('showMusic',e.target.checked)}/></label></>;
}

function StylePanel({section,config,patch,patchTextStyle,uploadConfig,uploading}:{section:SectionKey;config:Config;patch:<K extends keyof Config>(key:K,value:Config[K])=>void;patchTextStyle:(key:TextStyleKey,value:TextPatch)=>void;uploadConfig:(file:File|undefined,key:keyof Config)=>void;uploading:boolean}){
 const textGroups:Partial<Record<SectionKey,{key:TextStyleKey;label:string}[]>>={
  hero:[{key:'heroCaption',label:'Hover title'}],
  work:[{key:'workKicker',label:'Small title'},{key:'workHeadline',label:'Headline'},{key:'workAside',label:'Aside'},{key:'workCardTitle',label:'Card title'},{key:'workCardMeta',label:'Card meta'}],
  about:[{key:'aboutKicker',label:'Small title'},{key:'aboutHeadline',label:'Headline'},{key:'aboutBody',label:'Body'},{key:'aboutDisciplines',label:'Disciplines'}],
  team:[{key:'teamKicker',label:'Small title'},{key:'teamHeadline',label:'Headline'},{key:'teamMemberName',label:'Member name'},{key:'teamMemberBio',label:'Member bio'},{key:'teamView',label:'View button'}]
 };
 return <div className="visual-style-panel">
  {section==='hero'&&<div className="visual-subpanel"><div className="visual-editor-panel-head"><strong>Main video gradient</strong><label className="visual-inline-toggle"><input type="checkbox" checked={config.heroFadeEnabled} onChange={e=>patch('heroFadeEnabled',e.target.checked)}/><span>{config.heroFadeEnabled?'ON':'OFF'}</span></label></div><p className="visual-help">상·하단을 각각 얇게 조절하면 훨씬 현대적인 페이드가 됩니다.</p><Range label="상단 그라데이션 크기" value={config.heroFadeTopSize} min={0} max={40} step={1} suffix="%" onChange={v=>patch('heroFadeTopSize',v)}/><Range label="하단 그라데이션 크기" value={config.heroFadeBottomSize} min={0} max={40} step={1} suffix="%" onChange={v=>patch('heroFadeBottomSize',v)}/><Range label="그라데이션 농도" value={config.heroFadeDensity} min={0} max={100} step={1} suffix="%" onChange={v=>patch('heroFadeDensity',v)}/><Range label="전체 불투명도" value={config.heroFadeOpacity} min={0} max={100} step={1} suffix="%" onChange={v=>patch('heroFadeOpacity',v)}/><Range label="페이드 블러" value={config.heroFadeBlur} min={0} max={40} step={1} suffix="px" onChange={v=>patch('heroFadeBlur',v)}/></div>}
  {!!textGroups[section]?.length&&<div className="visual-subpanel"><div className="visual-editor-panel-head"><strong>Typography</strong></div>{textGroups[section]!.map(item=><TextStyleControl key={item.key} label={item.label} value={config.textStyles[item.key]} onChange={v=>patchTextStyle(item.key,v)}/>)}</div>}
  <div className="visual-subpanel"><div className="visual-editor-panel-head"><strong>Site style</strong></div><div className="visual-segmented"><button className={config.theme==='dark'?'is-active':''} onClick={()=>patch('theme','dark')}>Dark</button><button className={config.theme==='light'?'is-active':''} onClick={()=>patch('theme','light')}>Light</button></div><label className="visual-color"><span>Accent</span><input type="color" value={config.accent} onChange={e=>patch('accent',e.target.value)}/><b>{config.accent.toUpperCase()}</b></label><label className="visual-field"><span>Font</span><select value={config.font} onChange={e=>patch('font',e.target.value)}><option>Arial, Helvetica, sans-serif</option><option>Helvetica Neue, Arial, sans-serif</option><option>Georgia, serif</option><option>Times New Roman, serif</option><option>Verdana, sans-serif</option><option>Courier New, monospace</option><option>system-ui, sans-serif</option></select></label><Range label="Body size" value={config.fontSize} min={12} max={24} step={1} suffix="px" onChange={v=>patch('fontSize',v)}/><Range label="Corner radius" value={config.radius} min={0} max={54} step={1} suffix="px" onChange={v=>patch('radius',v)}/><Range label="Glass blur" value={config.blur} min={0} max={60} step={1} suffix="px" onChange={v=>patch('blur',v)}/><Range label="Glass opacity" value={config.glass} min={10} max={100} step={1} suffix="%" onChange={v=>patch('glass',v)}/><Range label="Motion" value={Math.round(config.motion*100)} min={0} max={180} step={5} suffix="%" onChange={v=>patch('motion',v/100)}/></div>
  <div className="visual-subpanel"><div className="visual-editor-panel-head"><strong>Background & pattern</strong></div><label className="visual-field"><span>Background</span><select value={config.backgroundType} onChange={e=>patch('backgroundType',e.target.value)}><option value="none">None</option><option value="image">Image</option><option value="video">Video</option></select></label>{config.backgroundType==='image'&&<FileField label="Background image" accept="image/*" disabled={uploading} value={config.backgroundImage} onFile={f=>uploadConfig(f,'backgroundImage')} onClear={()=>patch('backgroundImage','')}/>} {config.backgroundType==='video'&&<FileField label="Background video" accept="video/mp4,video/webm" disabled={uploading} value={config.backgroundVideo} onFile={f=>uploadConfig(f,'backgroundVideo')} onClear={()=>patch('backgroundVideo','')}/>} {config.backgroundType!=='none'&&<><Range label="Background opacity" value={config.backgroundOpacity} min={0} max={100} step={1} suffix="%" onChange={v=>patch('backgroundOpacity',v)}/><Range label="Background dim" value={config.backgroundDim} min={0} max={100} step={1} suffix="%" onChange={v=>patch('backgroundDim',v)}/></>}<label className="visual-field"><span>Pattern</span><select value={config.pattern} onChange={e=>patch('pattern',e.target.value)}><option value="none">None</option><option value="dots">Dots</option><option value="grid">Grid</option><option value="diagonal">Diagonal</option><option value="checker">Checker</option><option value="lines">Lines</option><option value="rings">Rings</option></select></label>{config.pattern!=='none'&&<><label className="visual-color"><span>Pattern color</span><input type="color" value={config.patternColor} onChange={e=>patch('patternColor',e.target.value)}/><b>{config.patternColor.toUpperCase()}</b></label><Range label="Pattern size" value={config.patternSize} min={8} max={120} step={1} suffix="px" onChange={v=>patch('patternSize',v)}/><Range label="Pattern opacity" value={config.patternOpacity} min={0} max={100} step={1} suffix="%" onChange={v=>patch('patternOpacity',v)}/></>}</div>
  <div className="visual-subpanel"><div className="visual-editor-panel-head"><strong>Browser</strong></div><TextField label="Browser title" value={config.browserTitle} onChange={v=>patch('browserTitle',v)}/><FileField label="Favicon" accept="image/png,image/jpeg,image/webp,image/x-icon,.ico" disabled={uploading} value={config.favicon} onFile={f=>uploadConfig(f,'favicon')} onClear={()=>patch('favicon','')}/></div>
 </div>;
}
function TextStyleControl({label,value,onChange}:{label:string;value:Config['textStyles'][TextStyleKey];onChange:(value:TextPatch)=>void}){
 const weight=value.weight??500,opacity=value.opacity??100,letterSpacing=value.letterSpacing??0,textTransform=value.textTransform??'none';
 return <details className="visual-text-style"><summary>{label}<span>{value.size}px · {weight}</span></summary>
  <label className="visual-field"><span>Font</span><select value={value.font} onChange={e=>onChange({font:e.target.value})}><option>Arial, Helvetica, sans-serif</option><option>Helvetica Neue, Arial, sans-serif</option><option>Georgia, serif</option><option>Times New Roman, serif</option><option>Verdana, sans-serif</option><option>Trebuchet MS, sans-serif</option><option>Courier New, monospace</option><option>system-ui, sans-serif</option></select></label>
  <Range label="Size" value={value.size} min={8} max={180} step={1} suffix="px" onChange={v=>onChange({size:v})}/>
  <Range label="X" value={value.x} min={-600} max={600} step={1} suffix="px" onChange={v=>onChange({x:v})}/>
  <Range label="Y" value={value.y} min={-420} max={420} step={1} suffix="px" onChange={v=>onChange({y:v})}/>
  <Range label="Letter spacing" value={letterSpacing} min={-8} max={24} step={.25} suffix="px" onChange={v=>onChange({letterSpacing:v})}/>
  <Range label="Weight" value={weight} min={100} max={900} step={100} onChange={v=>onChange({weight:v})}/>
  <Range label="Opacity" value={opacity} min={0} max={100} step={1} suffix="%" onChange={v=>onChange({opacity:v})}/>
  <label className="visual-color"><span>Color</span><input type="color" value={value.color||'#ffffff'} onChange={e=>onChange({color:e.target.value})}/><b>{value.color||'AUTO'}</b></label>
  <label className="visual-field"><span>Text case</span><select value={textTransform} onChange={e=>onChange({textTransform:e.target.value as TextPatch['textTransform']})}><option value="none">As typed</option><option value="uppercase">UPPERCASE</option><option value="lowercase">lowercase</option><option value="capitalize">Capitalize</option></select></label>
  <div className="visual-align-buttons">{(['left','center','right'] as const).map(a=><button key={a} className={value.align===a?'is-active':''} onClick={()=>onChange({align:a})}>{a}</button>)}</div>
 </details>;
}
function WorkEditor({work,patch,onUpload,uploading,onDuplicate,onDelete}:{work:Work;patch:(key:keyof Work,value:Work[keyof Work])=>void;onUpload:(file:File|undefined,field:'poster'|'video')=>void;uploading:boolean;onDuplicate:()=>void;onDelete:()=>void}){
 return <><div className="visual-editor-panel-head"><h3>Work card</h3><div><button type="button" title="복제" onClick={onDuplicate}><Copy size={13}/></button><button type="button" className="is-danger" title="삭제" onClick={onDelete}><Trash2 size={13}/></button></div></div><TextField label="Title" value={work.title} onChange={v=>patch('title',v)}/><TextField label="Category" value={work.category} onChange={v=>patch('category',v)}/><TextField label="Year" value={work.year} onChange={v=>patch('year',v)}/><TextField label="Role" value={work.role} onChange={v=>patch('role',v)}/><TextField label="Description" value={work.description} multi onChange={v=>patch('description',v)}/><label className="visual-toggle"><span>공개</span><input type="checkbox" checked={work.visible} onChange={e=>patch('visible',e.target.checked)}/></label><FileField label="Poster / Image" accept="image/jpeg,image/png,image/webp" disabled={uploading} value={work.poster} onFile={f=>onUpload(f,'poster')} onClear={()=>patch('poster','')}/><FileField label="Video" accept="video/mp4,video/webm" disabled={uploading} value={work.video} onFile={f=>onUpload(f,'video')} onClear={()=>patch('video','')}/></>;
}
